### ISSUE TITLE
I also want to read CSS file and use variables in IE10.

### ISSUE THREAD

**Issue by Tsutomu-Fujii** [jhildenbiddle/css-vars-ponyfill#10]
Nice to meet you, Mr. jhildenbiddle
My name is Fujii Tsutomi.
Thank you for exposing a wonderful system.

May I ask a question?
● I also want to read CSS file and use variables in IE10.

  ■ Tested with the development tool of IE11.
     I tested it with "Internet Explorer 10" and "Internet Explorer 11".

  ■ When reading an ICSS file <link herf = "">, in "Internet Explorer 10"
    'Access - Control - Allow - Origin ~~~~' will cause an error.

![2018y05m19d_225917595](https://user-images.githubusercontent.com/39436757/40269387-ca31e5ac-5bb8-11e8-9646-08f14f258f52.png)

  ■ I This is my sample page. If you do not mind, can you confirm? (F 12)
   [ https://testtesttest21.sakura.ne.jp/sample/testtest/]( https://testtesttest21.sakura.ne.jp/sample/testtest/)

  ■ I The following is the log displayed on the console.

SEC 7120: The original https://testtesttest21.sakura.ne.jp is not found in the Access-Control-Allow-Origin header.
testtest
CSS XHR error: "undefined" undefined
 [object HTMLLinkElement]
   "CSS XHR error:" undefined "undefined
"
   <link href = "sss.css" rel = "stylesheet"> </ link>
"

● If you have a good method, would you please tell me?

Above, thank you.

**Comment by jhildenbiddle** [comment]
Nice to meet you, @Tsutomu-Fujii. 😄 

The error is caused by the following HTML/CSS:

```html
<style>
  @import "./sss.css";
</style>
```

The file `sss.css` does not exist at the specified location which results in a [404 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404). Strangely, the error you are seeing in IE11 in "IE10 mode" incorrectly indicates a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error:

```
Origin https://testtesttest21.sakura.ne.jp not found in Access-Control-Allow-Origin header.
```

This is just strange "IE11 running in IE10 mode" behavior. If you switch IE11 back to its default "IE11 mode" you will see that the error is reported properly as a 404.

```
CSS XHR error: "undefined" 404
```

If you fix the broken path to `sss.css`, the issue should be resolved.

Hope this helps!

**Comment by Tsutomu-Fujii** [comment]
Thank you for the fast response! !

I will fix it and think for myself a little.

I am very grateful to you.

**Comment by jhildenbiddle** [comment]
Happy to help.

I've updated the ponyfill to provide better error details in the console. Hopefully this will help others who run into similar issues.
