### ISSUE TITLE
Include doesn't work

### ISSUE THREAD

**Issue by RaulJimenezGarcia** [jhildenbiddle/css-vars-ponyfill#101]
Hi,

I'm trying to filter just one style tag of my page by its id.

I initialize cssVars this way:
```
cssVars({
  include: '#sidebar-styles'
});
```
However cssVars is including two other link tags of my page.

My page has more than two link tags and their paths are all relative.

Any help will be appreciated.

**Comment by jhildenbiddle** [comment]
Can you create a demo ([CodeSandbox](https://codesandbox.io/), [StackBlitz](https://stackblitz.com/)) with your HTML and stylesheets so I can review?

**Comment by RaulJimenezGarcia** [comment]
I'll try to do it.

Adding a little more info, it seems to work properly when I initialize cssVars on page load.

However, when I update the value of two variables at runtime, cssVars inserts in the DOM the content of two not included css files.

Both not included files are the only two containing css variables among all the css files I load.

The way I update the variables is:

<pre>
  cssVars({
    variables: {
      '--js-w': currentWidth + 'px',
      '--js-negative-margin-left': newDesplacement + 'px',
    }
  });
</pre>

**Comment by jhildenbiddle** [comment]
You will need to set the `include` key and value each time you call `cssVars()`. Otherwise, the library will use the default values.

```js
  cssVars({
    include: '#sidebar-styles',
    variables: {
      '--js-w': currentWidth + 'px',
      '--js-negative-margin-left': newDesplacement + 'px',
    }
  });
```

If you plan to call the ponyfill multiple times throughout your code and don't want to rewrite your options each time, store you configuration separately and reuse it:

```js
// Options
const cssVarsConfig = {
  include: '#sidebar-styles'
};

// First call
cssVars(Object.assign({}, cssVarsConfig, {
  variables: {
    '--color': 'red'
  }
}));

// Second call
cssVars(Object.assign({}, cssVarsConfig, {
  variables: {
    '--color': 'blue'
  }
}));
```

Keep in mind that legacy browsers like IE don't support [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) so you will need to polyfill, use a library, use a transpiler, or write your own function to handle duplicating and merging objects.
