### ISSUE TITLE
Examples of callbacks are broken?

### ISSUE THREAD

**Issue by pbb72** [jhildenbiddle/css-vars-ponyfill#115]
I guess I am overlooking something here, but it seems to me like all examples of callback usage are broken?

For example, at https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=oncomplete
```javascript
cssVars({
  onComplete(cssText, styleElms, cssVariables, benchmark) {
    // ...
  }
});
```

This causes IE11 to balk with **SCRIPT1003: Expected ':'**. Which seems logical to me, because you provide cssVars with an object, but then have a function inside it without property name.

Searching around for a solution, nearly all examples I find use this format. But then in the end I found the Codepen demo, which uses
```javascript
cssVars({
  onComplete: function(cssText, styleElms, cssVariables, benchmark) {
    // ...
  }
});
```

And this works in IE11.

Now, since almost all examples I found were using the first format, I am pretty sure there is something that I am doing wrong. But I would love to hear what is going on here. Or maybe nobody uses this functionality in Internet Explorer?

**Comment by jhildenbiddle** [comment]
The examples are all using the [shorthand method definition syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) provide by ES6.

Instead of this (ES5):

```js
var myObj = {
  myMethod: function() {
    // ...
  }
};
```

ES6 allows you to drop the `function` keyword:

```js
var myObj = {
  myMethod() {
    // ...
  }
};
```

To be honest, I wrote the example this way simply out of habit as I've become accustomed to writing all JS in ES6+ and transpiling back to ES5 with [Babel](https://babeljs.io/) + parcel/rollup/webpack/etc. Given that this library is designed to support legacy browsers, it makes more sense to provide example using legacy-compatible ES5 syntax.

Thanks fo the heads up. I'll update the docs accordingly.
