### ISSUE TITLE
Alternate stylesheets on IE11 broken

### ISSUE THREAD

**Issue by pbb72** [jhildenbiddle/css-vars-ponyfill#116]
Give the following HTML file head:
```html
<style>
:root {
  --blue: blue;
  --green: green;
}
</style>
<link href="blue-on-yellow.css" rel="stylesheet" type="text/css" title="Default Style">
<link href="green-on-red.css" rel="alternate stylesheet" type="text/css" title="Alternate Style">
<script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2.2.1/dist/css-vars-ponyfill.min.js"></script>
<script>cssVars();</script>
```

And the following CSS files.
blue-on-yellow.css:
```css
* {
	color: var(--blue);
	background: yellow;
}
```
green-on-red.css:
```css
* {
	color: var(--green);
	background: red;
}
```

And then switching styles in Internet Explorer using Alt (to unhide menu bar) > View > Style, you will **always** see blue text, even though the background color changes between yellow and red.

This is not a problem with precedence or order; the blue-on-yellow.css should be completely ignored when the Alternate Style is active.

**Comment by jhildenbiddle** [comment]
The ponyfill currently does not support toggling alternate stylesheets via the browser's native style switcher for three reasons: 1) a simple solution isn't possible, 2) a complex solution isn't worth doing, and 3) it's relatively easy to create your own stylesheet switcher that addresses the issues from the previous two items.

#### 1) A simple solution isn't possible

The native stylesheet switchers offered in browsers like IE and Firefox provide no mechanism to detect when the user has selected an alternate stylesheet: no event is fired, no DOM mutation is made, no stylesheets are enabled/disabled, etc. If they did, it would be relatively simple to automatically call the ponyfill when a stylesheet change is detected. Since they don't, the only options left are hacky (like polling to detect stylesheet changes) or more complex solutions...

#### 2) A complex solution isn't worth doing

Native stylesheet switchers are available on only a small subset of browsers--most notably, IE and Firefox on the desktop. Even if a simple solution was possible, it would only benefit a very, very small percentage of users--A) users on IE or (very old) Firefox that B) want to change to an alternate stylesheet and C) are aware that their browser offers this functionality under the "View" menu. Said another way, if switching stylesheets is a feature you want to make available to your users, relying on the browser's native switcher is the wrong way to do it.

That said, a solution is possible but it is not trivial. The complicating factors are custom properties defined in alternate stylesheets and alternate stylesheet groups. Rather than go into details about the solution (since it would take a bit of time to explain), I'll just say that while the example you've given above is straightforward the ponyfill would also need to support the following example in order to say it properly supports alternate stylesheets:

```html
<link rel="stylesheet" href="path/to/file.css">
<link rel="stylesheet" href="path/to/file.css" title="Group 1">
<link rel="alternate stylesheet" href="path/to/file.css" title="Group 1">
<link rel="alternate stylesheet" href="path/to/file.css" title="Group 2">
<link rel="alternate stylesheet" href="path/to/file.css" title="Group 2">
<link rel="alternate stylesheet" href="path/to/file.css" title="No Group">
<style>
:root {
  --color: red;
}
</style>
```

Assume none, some, or all of the alternate stylesheets contain their own custom property declarations which should only be applied when the stylesheet(s) are active.

```css
:root {
  --color: green;
}
```

#### 3) It's relatively easy to create your own stylesheet switcher

Fortunately, it's not very difficult to create your own [style sheet switcher](https://www.google.com/search?q=style+sheet+switcher) that works with the ponyfill. Doing so also ensures that the functionality is available in all browsers, not just the ones that have native style switchers (like IE and Firefox). This is accomplished by enabling/disabling stylesheets via `document.stylesheets` (not adding/removing a `disabled` attribute on `<link>` and `<style>` nodes).

1. Use `rel="alternate stylesheet"` and `title="..."` attributes on `<link>` and `<style>` nodes as usual to allow default styles to be applied to the DOM.
2. Use JavaScript to set the `disabled` property to `true` or `false` on individual stylesheets via `document.stylesheets` (not on the `<link>` or `<style>` node) enable/disable stylesheets.
3. Remove the `alternate` keyword from the `rel` attribute of the `<link>` node(s) being enabled. You can access the `<link>` node from a specific stylesheet via the `ownerNode` property (e.g. `document.stylesheets[0].ownerNode`).
4. Run the ponyfill to generate new legacy-compatible CSS.

Hope this helps.

**Comment by pbb72** [comment]
Thanks for the extensive write-up! I fully agree with you that alternate stylesheets are extremely little used, and do not justify using much time on fixing issues.

**Comment by pbb72** [comment]
Got it working with your info, thanks. Just FYI, it seems Chrome is lazy-loading alternate stylesheets. Even after loading the complete DOM, `doument.styleSheets` only contained the active stylesheets. I had to do a wait before alternate stylesheets were included, However, it worked like a charm with setting `disabled` on the DOM link elements. The `alternate` keyword needs to be removed to get the ponyfill to work (not required for pure style switching).

```javascript
if (location.search == "?standard") localStorage.removeItem("stile");
if (location.search == "?new") localStorage.setItem("style","new");
if (location.search == "?dark") localStorage.setItem("stiye","dark");
let style = localStorage.getItem("style");
if (style) {
   const styleSheets = document.querySelectorAll("link[rel][title]");
   for (let i = 0; i < styleSheets.length; i++) {
      const ss = styleSheets[i];
      if (ss.title == style)
        ss.rel = "stylesheet";
      else
        ss.disabled = true;
   }
}
```

**Comment by jhildenbiddle** [comment]
Happy to hear you got it working. Two things worth mentioning:

1. Browser support for the `disabled` property on `<link>` elements is inconsistent. You’ll get more reliable results setting the `disabled` property on the stylesheet object via `document.stylesheets` (or you can access a stylesheet object directly from a `<link>` or `<style>` element using `element.sheet`). I believe setting the `disabled` property on a `<link>` element in Chrome just sets the `disabled` property on the stylesheet object for you. See here for details: https://github.com/whatwg/html/issues/3840

1. Safari has some interesting quirks when it comes to enabling/disabling alternate stylesheets. I don’t remember the exact details, but if memory serves it involved enabling a stylesheet so it could be disabled or visa versa. Perhaps this is a non-issue for the latest version, but I remember specifically having to work around it in the past.

Both of these are just FYIs in case you’re only testing in Chrome.
