### ISSUE TITLE
IE does not support calc() on color functions.

### ISSUE THREAD

**Issue by mixaDev** [jhildenbiddle/css-vars-ponyfill#118]
before
`hsl(var(--color-h), var(--color-s), calc(var(--color-l) * 0.95))`
after
`hsl(0, 0%, calc(95.3% * 0.95))`
need
`hsl(0, 0%, 90.5%)`

**Comment by jhildenbiddle** [comment]
IE's inability to process `calc()` functions nested within color functions is one of many known calc-related issues. Here is a complete list of known issues borrowed from https://caniuse.com/#search=calc:

> * Firefox <66 does not support width: calc() on table cells. Bug Report
> * Firefox <59 does not support calc() on color functions. Example: color: hsl(calc(60 * 2), 100%, 50%). Bug Report
> * IE does not support calc() on color functions. Example: color: hsl(calc(60 * 2), 100%, 50%).
> * Firefox <48 does not support calc() inside the line-height, stroke-width, stroke-dashoffset, and stroke-dasharray properties. Bug report
> * IE & Edge are reported to not support calc inside a 'flex'. (Not tested on older versions)
This example does not work: flex: 1 1 calc(50% - 20px);
> * IE11 does not support transitioning values set with calc()
> * Safari & iOS Safari (both 6 and 7) does not support viewport units (vw, vh, etc) in calc().
> * IE11 is reported to have trouble with calc() with nested expressions, e.g. width: calc((100% - 10px) / 3); (i.e. it rounds differently)
> * IE11 is reported to not support calc() correctly in generated content
> * IE10, IE11, and Edge < 14 don't support using calc() inside a transform. Bug report
> * IE 9 - 11 don't render box-shadow when calc() is used for any of the values
> * IE10 crashes when a div with a property using calc() has a child with same property with inherit.
> * IE 9 - 11 and Edge do not support width: calc() on table cells. Bug Report

The goal of the ponyfill is to resolve custom property `var()` functions to static values. It is not intended to fix browser-specific bugs that may result from that process--not because it can't, but because the list of things-to-be-fixed goes well beyond the scope of making custom properties work in legacy browsers.

**Comment by mixaDev** [comment]
I need a hook similar to onSuccess, after processing, but before pasting into the DOM, where I can calculate calc ()

**Comment by jhildenbiddle** [comment]
@mixaDev --

A hook as you describe (e.g. a new `onTranspiled()` callback or something similar) would allow you to parse an entire block of transpiled CSS, but doing so will require more work than simply iterating over the existing stylesheet objects. 

The following example `onComplete` callback will give you access to each style declaration property and value. Some basic checking is done to avoid iterating over stylesheets and rules that do not contain a color function with a nested `calc()` function. The important takeaway (IMHO) is that properly evaluating `calc` expressions is a non-trivial task, so I'd focus on that first before worrying how you access the CSS to be parsed.

```js
cssVars({
  onComplete: function(cssText, styleElms, cssVariables, benchmark) {
    var hasColorFunctionWithCalc = /(?:hsl|rgb)a?\(.*calc\(/;
      
      // Iterate over <style> elements created by the ponyfill
      styleElms.forEach(function(styleElm) {
        // Test CSS for a color function with nested calc() function
        if (hasColorFunctionWithCalc.test(styleElm.textContent)) {
          var cssRules = styleElm.sheet.cssRules;
          
          // Iterate over cssRules
          for (var i = 0; i < cssRules.length; i++) {
            var rule = cssRules[i];

            // Test rule for a color function with nested calc() function
            if (hasColorFunctionWithCalc.test(rule.cssText)) {
              
              // Iterate over style declarations
              for (var j = 0; j < rule.style.length; j++) {
                var prop = rule.style[j]; // Ex: "color"
                var value = rule.style[prop]; // Ex: "rgb(255, 0, 0)"
                
                // Now the hard part:
                // 1. Parse the value for color function with nested calc() function
                //    Ex1: hsl(calc(...) ...)
                //    Ex1: hsla(calc(...) ...)
                //    Ex1: rgb(calc(...) ...)
                //    Ex1: rgba(calc(...) ...)
                // 2. Parse the nested calc function(s) for math expression(s)
                //    Ex1: calc(1 + 2)
                //    Ex2: calc(calc(1 + 2) + calc(3 + 4))
                //    Ex3: calc(1 + calc(2 + calc(3 + 4)))
                // 3. Determine if the expression(s) can be evaluated
                //    Ex1: 1 + 1 = YES (matched unit-less)
                //    Ex2: 1px * 1 = YES (unit and unit-less multiplication)
                //    Ex3: 1px / 1 = YES (unit and unit-less division)
                //    Ex4: 1px + 1px = YES (matched units)
                //    Ex5: 1in + 1cm = YES (convertible mixed units)
                //    Ex6: 1px + 1 = NO (unit and unit-less addition)
                //    Ex7: 1px - 1 = NO (unit and unit-less subtraction)
                //    Ex8: 1px + 1em = NO (non-convertible mixed units)
                // 4. Evaluate expression(s)
                // 5. Generate new CSS value
                // 6. Set style or insert rule with new value
                
                console.log(prop, value);
              }
            }
          }
        }
      });
    }
  });
```

**Comment by mixaDev** [comment]
@jhildenbiddle 

1. `postcss-calc` && `postcss-custom-properties` for many reasons did not fit
2. `onComplete`... also did not fit
IE11
styleElm.textContent => 'a{color: hsl(0, 0%, calc(95.3% * 0.95))}'
styleElm.sheet.cssRules[i].cssText => ''
styleElm.sheet.cssRules[i].style.length => 0
IE does not apply invalid rules in cssRules
3. I need to protect calc only this kind
`hsl(var(--color-h), var(--color-s), calc(var(--color-l) * 0.95))`
I did it `onSuccess` with a regexp
https://github.com/cloudipsp/checkout-vue/blob/2bf0e346358f5300b4a79360a75a1e0dc208222f/src/store/css-variable.js#L82

**Comment by jhildenbiddle** [comment]
@mixaDev --

I didn't realize IE would see a declaration that used a color function with a nested `calc()` function as invalid. I did know that some browsers (like IE) remove invalid rules from the stylesheet, but I assumed IE would retain the declaration since it understands `calc()` even if it can't process it correctly.

Regardless, I'm not opposed to implementing another callback but I a generally try to avoid adding yet-another-option when possible. In that spirit, here are two other options to consider:

1. Use the `onComplete` callback to iterate over the `<style>` elements appended to the DOM by the ponyfill, parse the `textContent`, replace strings as needed, then update the `textContent` when the work is complete. If you are only processing `<style>` elements (and no `<link>` elements), there will likely be no performance impact because the ponyfill processes `<style>` elements synchronously. If you are processing `<link>` elements as well, then the downside to this approach is that you will be replacing the `textContent` of a stylesheet that has already been parsed and applied to the DOM, so the browser will have to re-parse-and-apply after you make your changes. That said, it's worth trying at least as a proof of concept and as a means to measure the performance impact.

1. You can force IE to retain declarations by prepending a `-` to it. These declarations won't do anything on their own, but IE will add them to the stylesheet and their format will make them easy to identify. For example:

   ```css
   div {
     -background: rgb(calc(254 + 1, 0, 0); // Retained by IE
     background: rgb(calc(254 + 1, 0, 0); // Dropped by IE
   }
   ```

   To help identify properties that contain values that need to be processed, you can use a custom prefix:

   ```css
   div {
     -CSSVARS-background: rgb(calc(254 + 1, 0, 0); // Retained by IE
     background: rgb(calc(254 + 1, 0, 0); // Dropped by IE
   }
   ```

   This approach would allow you to iterate of the stylesheet properties and rules as described in my previous answer. The downside to this approach is that you have to manually edit your source CSS to work with the ponyfill.


Neither of the two approaches above are ideal, but they will both allow you to move forward.

Hope this helps.

**Comment by jhildenbiddle** [comment]
@mixaDev --

Checking in to see how things are going. Happy to help if needed.
