### ISSUE TITLE
element style attribute assignment

### ISSUE THREAD

**Issue by stutteringp0et** [jhildenbiddle/css-vars-ponyfill#12]
Any plans to support element level value assignment via the style tag?

    <h1 style="--h1-color:blue">this would be super nice</h1>

**Comment by jhildenbiddle** [comment]
It could be done, but not in the way your example suggests.

The ponyfill only supports `:root`-level declarations, but your example declares a custom property scoped to the `<h1>` tag (and all of its children). This won't be supported because it is not possible do so in a spec-compliant way (see #5 for details).

What *could* be added is the ability to transform inline custom property values to static values. For example:

```css
:root {
  --h1-color: blue;
}
```

```html
<!-- Before -->
<h1 style="color: var(--h1-color)">this would be super nice</h1>

<!-- After with options.preserve: false (default)-->
<h1 style="color: blue;">this would be super nice</h1>

<!-- After with options.preserve: true -->
<h1 style="color: var(--h1-color); color: blue;">this would be super nice</h1>
```

I'm not sure if this addresses your needs though.

**Comment by stutteringp0et** [comment]
I was looking for feature parity with browsers.  Chrome, FF, Opera, Safari, Edge all support this.  I'm looking at this for IE11 only.
