### ISSUE TITLE
Question - Support for CSS Keyframe Animations?

### ISSUE THREAD

**Issue by pseudoramble** [jhildenbiddle/css-vars-ponyfill#13]
First, thanks for the ponyfill! We appreciate the effort put into this and has given us some hope of using modern CSS features in older browsers.

We are attempting to use this for a CSS keyframe animation, but it does not seem like the generated keyframe is being applied properly. It does look like `css-vars-ponyfill` is inserting the new values for variables as expected, but it seems as if it does not replace the keyframe with the updated values.

Our question is if there is something special we need to do for animations, or should this work as we would like?

Here is an example. This is the CSS we start with:

```
:root {
  --red: 123;
  --blue: 9;
  --green: 255;
}

@keyframes test {
  0% {
    box-shadow:0 -2.6em 0 0 rgba(var(--red), var(--green), var(--blue), 1);
  }

  100% {
    box-shadow:0 -2.6em 0 0 rgba(var(--green), var(--red), var(--blue), 1);
  }
```

When we run `css-vars-ponyfill`, we get the following style tag inserted:

```
<style id="css-vars-ponyfill">
/*__CSSVARSPONYFILL-1__*//*__CSSVARSPONYFILL-3__*//*__CSSVARSPONYFILL-5__*//*__CSSVARSPONYFILL-7__*//*__CSSVARSPONYFILL-9__*//*__CSSVARSPONYFILL-11__*//*__CSSVARSPONYFILL-13__*/@keyframes test{0%{box-shadow:0 -2.6em 0 0 rgba(27, 117, 187, 1);}100%{box-shadow:0 -2.6em 0 0 rgba(117, 27, 187, 1);}}
/*__CSSVARSPONYFILL-17__*//*__CSSVARSPONYFILL-19__*//*__CSSVARSPONYFILL-21__*//*__CSSVARSPONYFILL-23__*//*__CSSVARSPONYFILL-25__*//*__CSSVARSPONYFILL-27__*/
</style>
```

And when we perform an update on our code (`--red` is 123 and `--green` is 0 say) we get the following output:

```
<style id="css-vars-ponyfill">
/*__CSSVARSPONYFILL-1__*//*__CSSVARSPONYFILL-3__*//*__CSSVARSPONYFILL-5__*//*__CSSVARSPONYFILL-7__*//*__CSSVARSPONYFILL-9__*//*__CSSVARSPONYFILL-11__*//*__CSSVARSPONYFILL-13__*/@keyframes test{0%{box-shadow:0 -2.6em 0 0 rgba(123, 0, 0, 1);}100%{box-shadow:0 -2.6em 0 0 rgba(0, 123, 0, 1);}}
/*__CSSVARSPONYFILL-17__*//*__CSSVARSPONYFILL-19__*//*__CSSVARSPONYFILL-21__*//*__CSSVARSPONYFILL-23__*//*__CSSVARSPONYFILL-25__*//*__CSSVARSPONYFILL-27__*/
</style>
```

That seems correct to us, but it does not apply to the existing component as expected.

**Comment by pseudoramble** [comment]
That makes some sense. Our case does not use inline styles, which I can see how that would make it complex. I see what you've described in IE11 as well. So I took the time to update the JS to be a bit more representative of what we're attempting.

To clarify more, we're actually attempting to perform updates dynamically. In our case, the app has a dropdown that allows a user to select what color scheme they want (which ties to these variables). So the flow is roughly:

- Start the app up (we're using React + Storybook in this situation)
- The initial animation is rendered in IE (that works OK)

```
// Dependencies
import cssVars from 'css-vars-ponyfill';

// Stylesheets
import './style.css';

function fixInlineStyleNodes() {
  const hasNativeSupport = window.CSS && window.CSS.supports && window.CSS.supports('(--a: 0)');

  if (!hasNativeSupport) {
    const inlineAnimationNodes = document.querySelectorAll('[style*="animation"]');
    const animationNamePostfix = '__css-vars-keyframe__';

    Array.apply(null, inlineAnimationNodes).forEach(node => {
      node.style.animationName += animationNamePostfix;
      void node.offsetLeft;
      node.style.animationName = node.style.animationName.replace(animationNamePostfix, '');
    });
  }
}

cssVars({
  onlyVars: true,
  onComplete(cssText, styleNode) {
    // fixInlineStyleNodes();
  }
});

setTimeout(() => {
  console.info('update CSS vars');

  cssVars({
    onlyVars: true,
    variables: {
      '--red': 1,
      '--blue': 255,
      '--green': 1
    }
  });
}, 2500);
```

**Comment by jhildenbiddle** [comment]
Demo has been updated with a working solution:

* https://stackblitz.com/edit/css-vars-ponyfill-13

Notice the "Change Colors" button and the new "Variables (update)" element. When the button is pressed, random r/g/b color values are generated and applied which will affect the new element only.

A few interesting things:

1. Similar to the "inline styles" fix mentioned earlier, elements that are affected by dynamic keyframe changes need a kick in IE. To accomplish this, I've modified the previous fix for inline styles so that the same process (modify animation name -> reflow -> reset animation name) is applied to *every* node via the `onComplete` callback. Modifying the animation name for every node isn't ideal, but it provides a generic fix that requires no inspection (e.g. `window.getComputedStyle()` which is more expensive) or adding/removing of nodes (which destroys attached event listeners).

   Performance for processing all nodes is decent, but if you know exactly which element(s) need to be reset, you can pass them to the `fixKeyframes()` function as either a CSS selector (string), Array, Element, HTMLCollection, or NodeList.

   ```javacsript
   const elm1 = document.querySelector('#elm1');
   const elm2 = document.querySelector('#elm1');

   // CSS Selector
   fixKeyframes('.myclass');

   // Array
   fixKeyframes([elm1, elm2]);

   // NodeList
   fixKeyframes(document.querySelectorAll('.myclass'));

   // ... etc.
   ```

2. I noticed a minor bug while exploring your issue: If a value of `0` is set using the `variables` property, the following console warning is displayed:

   `CSS transform warning: variable "--myvar" is undefined`

   The ponyfill sets the value as expected, but the console warning should no appear. I'll fix this in the next release.

Thoughts on the fix? The fact that it involves modifying the animation name on *every* node leaves me hesitant to bake it into the ponyfill, but without it anyone using custom properties in keyframes will run into the same issues you have on IE.

**Comment by pseudoramble** [comment]
We pulled in the fix into our component to see how it would work. It seems to fare pretty well. It's somewhat peculiar code for our codebase, so ideally this would exist in the library. That being said, in the short term it'll be a fine fix for us.

With respect to testing all nodes - one option I can think of is requiring either a selector or a NodeList of elements to be updated. If the NodeList was empty, or the selector did not turn up any keyframe elements, no updates would be performed. At that point the reflow could be triggered on the individual elements found or given. It would be sort of an obscure setting though, and I can't quite think of what it would possibly be named.

Thanks again for all your help!

**Comment by jhildenbiddle** [comment]
Added in 1.8.0.

See [`options.watch`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionswatch) and the [changelog](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/CHANGELOG.md) for details.

It turns out IE is not the only browser with this issue. Surprisingly, even the latest version of Safari (desktop and iOS) requires the same "kick" to recognize dynamically updates keyframe values. If you test your app pre-fix, you should see the same behavior in both Safari and IE11.

The fix that has been baked into the ponyfill has additional optimizations. A similar version is available in the demo:

* https://stackblitz.com/edit/css-vars-ponyfill-13

The optimizations are as follows:

* Previous fix processed all nodes. New fix only processes nodes contained in the `body`.
* Previous fix recalculated layout after processing each node. New fix only recalculates layout once.
* Previous fix "kicked" *every* node, which could get noisy if a MutationObserver is observing `style` attribute mutations. New fix only "kicks" elements that have a keyframe animation assigned to them. This is faster, and cuts down on MutationObserver noise.

If you could update your dependency to 1.8.0 and let me know how it goes, I'd very much appreciate it.

Thanks for the suggestion and the discussion. Very much appreciated!

**Comment by pseudoramble** [comment]
Just upgraded and gave it a whirl - looks good on our end!

Thanks a ton for the effort on this. Seriously, this was a great experience!

**Comment by jhildenbiddle** [comment]
Excellent! Good to hear it is working well for.

Thanks again for taking the time to open the issue. This could have been a tricky issue for others to track down, so it's nice to have a fix baked into the ponyfill.

Two quick closing items:

1. Since you are using react, you may be interested in the new [`options.watch`](https://www.npmjs.com/package/css-vars-ponyfill#optionswatch) that was also added in 1.8.0.

1. I'm still curious as to why you were seeing the internal `/*__CSSVARSPONYFILL__*/` placeholders in your CSS output. Can you confirm that this is still the case, and if so, open a separate issue so I can track down the issue?

Thanks again, @pseudoramble. 😄

**Comment by pseudoramble** [comment]
I have been taking a look at the `/*__CSSVARSPONYFILL-XX__*/` issue this morning. I do still see it happening on our end. I'll open up a new issue so it doesn't get lost at the bottom of this one.
