### ISSUE TITLE
Using setProperty to reassign a variable.

### ISSUE THREAD

**Issue by Irfan434** [jhildenbiddle/css-vars-ponyfill#130]
Consider the CSS file:
```
:root {
    --blue: #00ff00;
    --red: #ff0000;
    --current: var(--blue);
}

.body {
    background-color: var(--current);
}
```
Suppose `var(--current)` is used in hundreds of places in the application. I want to dynamically change the app's colour scheme by assigning `--current` to `var(--red)`, like so:

```
const newColor = getComputedStyle(document.documentElement).getPropertyValue('--red');
document.documentElement.style.setProperty('--current', newColor);
```

Unfortunately the color does not change to red on Internet Explorer when using the ponyfill. It remains blue. I've used:

```
cssVars.default({
    shadowDOM: true
});
```

Thanks in advance.

**Comment by jhildenbiddle** [comment]
This is what [`options.variables`](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=variables) is designed for.

```js
cssVars({
  variables: {
    '--current': 'var(--red)'
  }
});
```

I've created a demo for you to review here: https://stackblitz.com/edit/css-vars-ponyfill-130?file=index.js

The reason `setProperty` doesn't work is because some browsers (like IE) drop declaration they don't understand. As a result, declarations like `--red: #ff000` are simply not available to methods like `getPropertyValue()`. The only way to retrieve this value is by reading the text content of the `<link>` element's `href` value or the `<style>` element, which is exactly what the ponyfill does.
