### ISSUE TITLE
Only working on IE11 after page refresh

### ISSUE THREAD

**Issue by mark-reason** [jhildenbiddle/css-vars-ponyfill#137]
Hi,

Thanks for this great ponyfill.

I have added this into a VueJS project but have run into an issue where when opening a new session of IE11 one of my CSS files is being skipped, the link element has the 'data-cssvars="skip"' attribute added, however if I perform a page refresh then it works and the file is picked up. Usage is currently as follows:

```
import cssVars from 'css-vars-ponyfill';

cssVars({
  watch: true
});
```

Any help would be greatly appreciated.

Cheers
Mark

**Comment by jhildenbiddle** [comment]
Hey @mark-reason.

A few ideas:

1. If the ponyfill adds `data-cssvars="skip"` to a `<style>` or `<link>` element it means the ponyfill did not detect a CSS custom property declaration (`--color: red`) or `var()` function. Can you confirm that the `<link>` stylesheet in question contains either a CSS custom property declaration or `var()` function? Note that you use can use the `onSuccess()` callback to inspect the CSS text that the ponyfill is processing for each stylesheet.

2. When are you calling the ponyfill? It sounds like there is a race condition at play, so perhaps calling the ponyfill after your Vue app/component(s) have initialized will address the issue. I'm not familiar with your app so it's hard to say.

Hope this helps. If not, let me know and we'll determine the next steps.

**Comment by mark-reason** [comment]
Hi @jhildenbiddle 

Thanks for the reply!

So the content of the file is as follows
```
:root {
  /* COLOURS */
  --primary-color-1: #391171;
  --primary-color-2: #299DDA;
  --primary-color-3: #5BC6B4;
  --primary-color-4: #F26177;
  --primary-color-5: #FFD251;
  --hover-color: #24094A;
  --bg-color-1: #FFF;
  --bg-color-2: #E7E1EE;
  --link-color: var(--primary-color-1);

  /* BUTTONS */
  --primary-btn-bg: var(--primary-color-1);
  --primary-btn-border: var(--primary-color-1);
  --primary-btn-text: #FFF;

  --primary-btn-hover-bg: var(--hover-color);
  --primary-btn-hover-border: var(--hover-color);
  --primary-btn-hover-text: #FFF;

  --primary-btn-focus-bg: var(--primary-color-1);
  --primary-btn-focus-border: var(--primary-color-2);
  --primary-btn-focus-text: #FFF;

  --primary-btn-active-bg: var(--hover-color);
  --primary-btn-active-border: var(--hover-color);
  --primary-btn-active-text: #FFF;

  --secondary-btn-bg: #FFF;
  --secondary-btn-border: var(--primary-color-1);
  --secondary-btn-text: var(--primary-color-1);

  --secondary-btn-hover-bg: #FFF;
  --secondary-btn-hover-border: var(--primary-color-2);
  --secondary-btn-hover-text: var(--primary-color-1);

  --secondary-btn-focus-bg: #FFF;
  --secondary-btn-focus-border: var(--primary-color-2);
  --secondary-btn-focus-text: var(--primary-color-1);

  --secondary-btn-active-bg: #FFF;
  --secondary-btn-active-border: var(--hover-color);
  --secondary-btn-active-text: var(--primary-color-1);

  --top-btn-bg: var(--primary-color-2);
  --top-btn-border: var(--primary-color-2);
  --top-btn-text: #FFF;

  --top-btn-hover-bg: var(--primary-color-1);
  --top-btn-hover-border: var(--primary-color-1);
  --top-btn-hover-text: #FFF;

  --top-btn-focus-bg: var(--primary-color-2);
  --top-btn-focus-border: var(--primary-color-1);
  --top-btn-focus-text: #FFF;

  --top-btn-active-bg: var(--hover-color);
  --top-btn-active-border: var(--hover-color);
  --top-btn-active-text: #FFF;

  /* TYPOGRAPHY */
  --h1-color: var(--primary-color-1);
  --h3-color: #F26177;
  --h4-color: #26201F;
  --headings-color: var(--primary-color-1);
  --light-text-color: #343434;

  /* ALERTS */
  --notification-bg: var(--primary-color-5);
  --notification-text: var(--primary-color-1);
  --confirmation-bg: var(--primary-color-3);
  --confirmation-text: var(--primary-color-1);
  --error-bg: #E02020;

  /* SECTIONS */
  --section-primary-border: var(--primary-color-3);
  --section-primary-heading: var(--primary-color-1);
  --section-secondary-border: var(--primary-color-4);
  --section-secondary-heading: var(--primary-color-1);

  /* FORMS */
  --input-focus-border: var(--primary-color-2);
}
```

And this gets loaded immediately after the opening body tag so it should get picked up?

I have just tried calling 'cssVars' in the mounted hook instead of loading it into the main.js file but still getting the same issue, skips it on first load of a new session but it works after a refresh.

Cheers
Mark

**Comment by mark-reason** [comment]
Any ideas on this one?

**Comment by jhildenbiddle** [comment]
Hey @mark-reason.

A few suggestions:

1. Try the latest version of the ponyfill that was released this morning (2.4.0). If it fixes your issue, then the issue is most likely that your app modified the `href` attribute after appending the `<link>` to the DOM which wasn't being detected properly in 2.3.x
1. Use the [`onSuccess`](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=onsuccess) callback to verify the URL and CSS content being processed by the ponyfill. This will help us understand why your `<link>` stylesheet is being tagged with `data-cssvars="skip"` by the ponyfill, which indicates no CSS custom property declarations or `var()` functions were detected.

   ```js
   cssVars({
     onSuccess(cssText, elm, url) {
       console.log('onSuccess', url, '\n' + cssText);
     }
   });
   ```
1. I'm assuming the CSS from your post above is just being served as a static file. If this is not the case and it is instead being injected by a CSS-in-JS library or generated dynamically in some way, this may be the issue. Try serving the CSS as a static file first to help narrow down the issue.

I've also created a basic Vue demo that uses the ponyfill to demonstrate how the ponyfill works:

* Editor: https://codesandbox.io/s/css-vars-ponyfill-137-mnzji
* Preview: https://mnzji.csb.app/

In the demo:

* The CSS from your post above is located in `/public/style.css`
* The CSS from your post above CSS is loaded via a `<link>` tag in the `<head>` element
  _FYI: I tried placing the `<link>` element inside the `<body>` tag, but codesandbox.io does some funky stuff and automatically moves it back to the `<head>` tag while rendering the page._
* The ponyfill can be called anytime (before/after `$mount()` or within a Vue lifecycle hook)
* The `<link>` element is properly tagged by the ponyfill with `data-cssvars="src"`

So, there's no issue with your CSS, the ponyfill, or an incompatibility with Vue. Just want to get that out of the way.

Now, notice that two other CSS files are loaded in the demo via `<link>` elements:

* `/public/skip.css`: A CSS file that contains no CSS custom property declarations or `var()` functions
* `/public/empty.css`: An empty CSS file

Using your browser's dev tools you can see that both `skip.css` and `empty.css` have been tagged by the ponyfill with `data-cssvars="skip"`. This is because the ponyfill did not detect either a CSS custom property declaration or `var()` function in these files. In the console, the [`onSuccess`](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=onsuccess) callback is logging the url and content of each stylesheet which can be used to verify exactly what the ponyfill is processing.

Hope this helps a bit. Let me know how the suggestions at the top of this comment go and we'll determine what the next steps are.

**Comment by mark-reason** [comment]
Hi @jhildenbiddle 

Thanks for your help here, hopefully starting to narrow this down now.

I can now see I am getting the following error in the console
`cssVars(): CSS XHR Error: https://dha-stroke-assets.s3.eu-west-2.amazonaws.com/dha-stroke-variables.css 0 Unspecified Error (possibly CORS related)`
This is strange as there is no CORS restriction on the assets and as you can see from the following screenshot, the file is successfully downloaded by the browser
![Screenshot 2020-11-06 at 11 04 44](https://user-images.githubusercontent.com/5191335/98359364-03385d80-2020-11eb-8438-c48ecbd71200.png)

It's only when the network states it has got the asset '(from cache)' (after refreshing the page) the file is not skipped.

Is there something I'm missing here?

Cheers
Mark

**Comment by jhildenbiddle** [comment]
Having the real URL to test with is helpful.

I've done some testing, and the best guess that I can come up with is that there is a CORS-related issue issue with your AWS configuration. This is based on test results of the following URLs:

```
http://dha-stroke-assets.s3.eu-west-2.amazonaws.com/dha-stroke-variables.css
https://dha-stroke-assets.s3.eu-west-2.amazonaws.com/dha-stroke-variables.css
```

* No issues with automated tests using `css-vars-ponyfill`, Chrome 86 (macOS), and IE11.
* No issues with automated tests using [`get-css-data`](https://github.com/jhildenbiddle/get-css-data) (the library responsible for collecting stylesheet data), Chrome 86 (macOS), and IE11.

I did, however, have two findings that may be of interest:

* I was able to get _one_ failed test on Chrome very early on during the above tests. Subsequent tests succeeded without issue, even after a browser restart and switching to incognito mode. This behavior feels like a [preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) issue to me, but since we're making a `GET` request I don't know why this would be the case.

  <img width="791" alt="Screen Shot 2020-11-06 at 5 16 24 PM" src="https://user-images.githubusercontent.com/442527/98739030-3f482700-236e-11eb-8b50-10631a17b633.png">

* While automated tests passed in the desktop browsers like Chrome and IE, those same tests to the URLs above would *always* fail when using Chrome in headless mode. This seems really odd to me: same browser, same version, same OS, same tests--but different behavior when making an `XMLHttpRequest`. I didn't spend too much time with this, but I'd love to know why this happens. Best guess on this one is that the request is somehow different when made from headless Chrome.

I'm not an AWS expert so take the following advise for what it's worth:

1. If possible, try [configuring your current AWS bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) (or setting up a test bucket) to accept all CORS requests. If this solves your issue, then you can revisit your previous configuration to determine what changes need to be made.
2. Use the ponyfill's [`onBeforeSend`](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=onbeforesend) option if there are specific headers you can send to address the issue
3. While less ideal, you may be able to work around the issue using `<link rel="prefetch">` or by manually making an ajax request to your AWS URL before the calling the ponyfill so that stylesheet data is already cached when the ponyfill makes its call.

Just some ideas. Wish I could provide you a more specific fix, but hopefully these will get you pointed in the right direction. If you are able to identify the issue, I'd love to know the details.

**Comment by mark-reason** [comment]
Thanks @jhildenbiddle.

I've had a go at changing the CORS settings but haven't got anywhere unfortunately. I've had to implement a workaround where I use Netlify's post processing snippet injection to add the CSS variable overrides and this is working fine so going to stick with that for now.

I really do appreciate your help on this, let me know if there's anywhere I can buy you a coffee for your trouble.

Cheers
Mark

**Comment by jhildenbiddle** [comment]
You bet, @mark-reason. Sorry we couldn't nail down the issue. Happy to hear you've got a workaround in place.
