### ISSUE TITLE
Lifecycle methods (onSuccess, onComplete, onError) are not executed when modern browser is used

### ISSUE THREAD

**Issue by pseudoramble** [jhildenbiddle/css-vars-ponyfill#14]
While working on https://github.com/jhildenbiddle/css-vars-ponyfill/issues/13 I stumbled upon the fact that the lifecycle method are not triggered. I sort of understand why this might be expected, because you won't have `cssText` available for example on completion, but I also found it somewhat confusing that it did not trigger anything and took me a while to realize what was happening.

I can think of three changes for this:

- Trigger the actions in both cases. This gets complex quickly because css-vars-ponyfill won't have access to the DOM node modified or the parsed CSS in that case.
- Log a message when a lifecycle method is specified in these cases. This will let the developer know that these will only be used in legacy browser mode and they should handle it.
- Add a different lifecycle method for this case (`onPropertiesSet`) perhaps. This might be confusing to differentiate between `onSuccess`/`onComplete`, but it would be a more explicit hook that both modes can share.

**Comment by jhildenbiddle** [comment]
Good point.

It's fair to assume that the `onComplete` callback will fire after the ponyfill has applied changes--regardless of whether it was done via injected `<style>` or `setProperty` method. As for the `onWarning` and `onError` callbacks, the scenarios which would trigger these callbacks don't apply when `options.variables` values are applied to modern browsers.

To prevent yet-another-callback, perhaps it would be best to just call the onComplete callback when `options.variables` values are applied to modern browsers as well? The arguments passed to the callback would be `null` for modern browsers when `onlyLegacy` is `true` (default) because there would be no `cssText` or `styleNode` available, but this difference could be used within the `onComplete` callback to determine if this is a modern or legacy browser.

For example:

```javascript
cssVars({
  variables: {
    '--color': 'red'
  },
  onComplete(cssText, styleNode) {
    // Legacy browser
    if (styleNode) {
      // ...
    }
    // Modern browser
    else {
      // ..
    }
  }
});
```

As a side note, the callback behavior you describe is mentioned in the `options.onlyLegacy` section of the docs. Not saying this addresses the issue in any way, but I thought it was worth mentioning. Would you have preferred to see the behavior described in another location as well?

**Comment by pseudoramble** [comment]
Wow, I completely missed it in the documentation. My mistake! I would suggest that if the code isn't modified to call `onComplete`, the docs should mention specifically *not* running those callbacks in the case of modern browsers. I don't think it would be perfectly clear to me even if I hadn't missed it.

The behavior you described makes sense to me. I do think that running a callback with null/undefined parameters might be confusing though, which is the downside to that approach. That being said, I don't think it sounds too strange. I think running `onComplete` in modern & legacy browsers would be a little more intuitive for people like me who aren't checking the docs carefully enough :)

BTW - If you'd like help with this, I'd be glad to get a PR started.

**Comment by jhildenbiddle** [comment]
Apologies for the delay on this, @pseudoramble.

I went back-and-forth a number of times on how to proceed with this issue. Long story short, I've decided to just update the [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables) section of the docs for now. 

If the issue comes up again, I will be explore other options like adding a new callback (which I now think is a better option than introducing potentially confusing onComplete behavior to address the issue). Until then, hopefully the updated docs will suffice.

If you feel strongly about the new callback, let me know and we can discuss further.

Thanks again, @pseudoramble. Really do appreciate the time and feedback. 😄
