### ISSUE TITLE
Version 2.4.0 IE11 incompatible. 

### ISSUE THREAD

**Issue by WrathZA** [jhildenbiddle/css-vars-ponyfill#141]
Hello!

Version 2.4.0 is causing issues on IE11

Error:

> SCRIPT438: Object doesn't support property or method 'forEach'
> css-vars-ponyfill@2 (8,15439)

It looks like while IE11 supports Array.forEach it doesn't support NodeList.foreach by default. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
versus
https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by jhildenbiddle** [comment]
Thanks for quickly filing the issue, @WrathZA.

This bug made me realize that my test setup is loading `@babel/preset-env` which is why [all tests were passing](https://travis-ci.org/github/jhildenbiddle/css-vars-ponyfill) instead of throwing an error in IE legacy browsers that don't support `forEach` on node lists.

Easy fix. I'll release a patch later tonight or tomorrow AM.

Thanks!
