### ISSUE TITLE
onComplete's cssText is empty when the css has changed within onSuccess but does not contain any css var

### ISSUE THREAD

**Issue by suspiration** [jhildenbiddle/css-vars-ponyfill#147]
Running into a weird issue that when a CSS does not contain any css variable, it seems to fail.  I have a scenario where some of my CSS does not have css variable, but I do need to replace some string within that CSS.  After doing that and returning the updated cssText within onSuccess, onComplete's cssText becomes empty.

See codepen here: https://codepen.io/suspiration/pen/YzWmvXO

Expected:
onComplete should contain the transformed cssText and add into the page.

Actual:
onComplete's cssText is empty.

**Comment by jhildenbiddle** [comment]
@suspiration --

The [demo](https://codepen.io/suspiration/pen/YzWmvXO) you linked to above is working as expected.

The ponyfill tries to do as little work as possible. One of the ways it does this is by skipping any `<link>` or `<style>` node that does not contain a custom property function (e.g., `var(--color)`) or `:root`-level declaration (e.g., `--color: red`). Neither the original CSS or the modified CSS returned from the `onSuccess()` callback in your demo contain a custom property function or declaration, so the ponyfill skips that node entirely.

To demonstrate, try the following CSS in your demo:

```css
:root {
  --size: 10px;
}

.test {
  display: block;
  line-height: var(--size);
}
```

You'll notice that after modifying the CSS in `onSuccess()`:

```js
cssText = cssText.replace('10px', '12px');`
```

The output is processed by the ponyfill:

```css
.test {
    display: block;
    line-height: 12px;
}
```

FWIW, if the goal is to simply modify strings within blocks of CSS text, you may want to check out [get-css-data](https://github.com/jhildenbiddle/get-css-data) or just loop over the `sheet` object of all `<link>` and `<style>` nodes and modify the properties directly via CSSOM. Both are better options than relying on this ponyfill to modify static values since it isn't really what the ponyfill was designed for.
