### ISSUE TITLE
CSS XHR error

### ISSUE THREAD

**Issue by steelraiden** [jhildenbiddle/css-vars-ponyfill#155]
Apparently, this happens when a css file is empty

![image](https://user-images.githubusercontent.com/40852479/110780549-1aed5000-8265-11eb-8133-6e821697e03a.png)

in function getUrls(urls) {
```js
if (xhr.status === 200 && isValidCss(xhr.responseText)) {
  onSuccess(xhr.responseText, i);
}
else if (xhr.status === 0 && isValidCss(xhr.responseText)) {
  onSuccess(xhr.responseText, i);
}
else {
  onError(xhr, i);
}
```

**Comment by jhildenbiddle** [comment]
Thanks @steelraiden. Easy fix. I'll try and get this out before EOD.

**Comment by jhildenbiddle** [comment]
@steelraiden --

This issue has been fixed in the [fix-155](https://github.com/jhildenbiddle/css-vars-ponyfill/tree/fix-155) branch. I'm currently waiting on feedback on #153 I hopes of combining both fixes in the next patch release. If I don't hear back on #153 by EOW, I will release this fix separately.

In the meaning, feel free to test out the [fix-155](https://github.com/jhildenbiddle/css-vars-ponyfill/tree/fix-155) branch to verify that it addresses your issue.

```
npm install --save jhildenbiddle/css-vars-ponyfill#fix-155
```

Thanks!
