### ISSUE TITLE
Can I use it in Nuxtjs?

### ISSUE THREAD

**Issue by XzyZachary** [jhildenbiddle/css-vars-ponyfill#167]
I want to use this polyfill in my nuxt project.  I saw this polyfill used in client side. Can I use it in server side?

**Comment by jhildenbiddle** [comment]
Hi @XzyZachary.

I'm not familiar with Nuxt.js, but I can tell you that the ponyfill requires a DOM environment to work properly. Unless your application is rendering static content on the server using JSOM or similar environment (which I doubt that it is for performance reasons), I do not believe the ponyfill will work on the server.

The good news is that the ponyfill shouldn't cause any issues if executed on the server because it only proceeds if a [basic browser check](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/9811bbdf64a1c6c476ffc3a074241dc342f2f18f/src/index.js#L12) is successful. When your page is served to the client, the ponyfill will execute as execute as expected.

Hope this answers your question. Let me know if there's more I can do to help.

**Comment by XzyZachary** [comment]
> 


Thank you very much, I saw that ssr is supported, so I asked.  But I implemented it by injecting the cssVars method by means of cdn.
