### ISSUE TITLE
Ponyfill doesn't work with CSSStylesheet.insertRule

### ISSUE THREAD

**Issue by vladbicu** [jhildenbiddle/css-vars-ponyfill#19]
Hi,

I'm working on a project that use [emotion-css](https://github.com/emotion-js/emotion) library + CSS vars. Because we had to support IE11, I tried to use this ponyfill. All things were great until we did a production build and the ponyfill didn't work. 

After some research I discovered that emotion library use insertRule API, which means that <style> tag is empty and the ponyfill has nothing to parse and replace. 

There's someone with this issue? Any ideas?

**Comment by jhildenbiddle** [comment]
Hi @vladbicu.

This is a relatively easy fix, but it comes with caveats.

Currently, CSS data is collected for `<style>` elements via the [`Node.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) property. As you've mentioned, this won't be reliable if a stylesheet has been modified using methods like [`deleteRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/deleteRule) or [`insertRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) because these modifications aren't reflected in the `Node.textContent` value. 

The fix requires iterating over the [`CSSRuleList`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList) of each `<style>` element and concatenating all [`CSSRule.cssText`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRule/cssText) values into a single string. This works, but there are two things to consider:

1. Iterating over potentially thousands of CSS rules is significantly slower than simply reading a `textContent` property. This is especially true with legacy browsers. For example, a Windows 10 VM on a 2009 Mac Pro @ 2.66GHz is able to generate CSS from the CSSRuleList of [bootstrap.min.css](https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css) in about 10ms running Chrome 69 and 30ms with IE11. These are number from a VM running on an older machine processing over 1000 CSS rules, but they help illustrate the point that the fix is much slower than the ~0ms it takes to read CSS data from `.textContent`.

   The way to mitigate this performance hit is to limit processing to only the CSS that *needs* to be processed. This can be done using either the [`include`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsinclude) or [`exclude`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsexclude) options. It looks like [emotion.js](https://github.com/emotion-js/emotion) adds a `data-emotion` attribute to the inserted `<style>` element, which makes this pretty easy (see below).

1. The fix will (potentially) produce different CSS output for each browser. This is because browsers can generate different runtime rules from the same CSS input based on how they handle unrecognized and vendor-prefixed properties and values. This is not a big deal functionally speaking, but it is different than how the ponyfill works today.

   Example CSS:
   ```
   body {
    -moz-appearance: none;
    -webkit-appearance: none;
   }
   ```

   Chrome / Safari CSSRule.cssText:
   ```
   body { -webkit-appearance: none; }
   ```

   Firefox CSSRule.cssText:
   ```
   body { -moz-appearance: none; }
   ```

   Edge / IE CSSRule.cssText:
   ```
   body { -moz-appearance: none; -webkit-appearance: none; }
   ```

All that being said, I think it makes sense to add an option for this scenario. I'm not familiar enough with the various CSS-in-JS libraries to know if this is a common issue, but it seems anyone modifying CSS using the `deleteRule()` or `insertRule()` methods would benefit.

Your final implementation would look something like this:

```javascript
cssVars({
  // Only process emotion.js <style> nodes
  include: 'style[data-emotion]'
  // Proposed option to generate CSS from CSSRuleList 
  useCSSRuleList: true
}) 
```

I'll put something together on a separate branch later on tonight. You can give it a test, see how it works, and if all is well I'll publish the changes to npm.

**Comment by jhildenbiddle** [comment]
I've created a [runtime](https://github.com/jhildenbiddle/css-vars-ponyfill/tree/runtime) branch with the fix described above. To install from this branch on GitHub using NPM: 

```javascript
npm i -D jhildenbiddle/css-vars-ponyfill#runtime
```

You can view the [`options.parseRuntime`](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/runtime/README.md#optionsparseruntime) docs in the same branch. Let me know if this addresses your issue and if you have any feedback.

**Comment by jhildenbiddle** [comment]
Well, that didn't go as planned.

Turns out the fix doesn't work in legacy browsers. I was testing in the latest version of Chrome which worked fine. Once I ran the full test suite, I noticed that the new `options.parseRuntime` test is failing in all legacy browsers. 

The reason for the failure is due to the browser behavior I described above:

> [...] browsers can generate different runtime rules from the same CSS input based on how they handle unrecognized and vendor-prefixed properties and values.

Legacy browsers don't understand CSS custom properties, so when a rule is inserted that contains one it is dropped from the `CSSRule.cssText` value. For example:

```javacsript
// Insert two rules into an empty stylesheet (like emotions.js)
styleElm.sheet.insertRule(':root { --color: red; }', 0); // 1
styleElm.sheet.insertRule('p { color: var(--color); }', 0); // 2

// Modern browser CSSRuleList
// 1: ':root { --color: red; }'
// 2: 'p { color: var(--color); }'

// Legacy browser CSSRuleList (e.g. IE)
// 1: ':root {  }'
// 2: 'p {  }'
```

Given this, I don't think it is possible to have the ponyfill work with stylesheets that use `deleteRule()` or `insertRule()` to manage rules that contain CSS custom properties.

One last thought...

You mentioned that everything was working fine until you did a production build. Does this mean the emotion.js behaves differently in production vs development mode? If so, is it possible to force emotion.js to behave as it does in development mode only for legacy browsers?

**Comment by vladbicu** [comment]
Hi @jhildenbiddle,

Thanks for the effort! Maybe will help some people that use insertRule/deleteRule API. 
Emotion library use the .insertRule API in production because it's fast and i don't  think they will change that. At this point i have two options:

1) Drop IE11 support
2) Replace emotion CSS with something else

**Comment by jhildenbiddle** [comment]
Sorry we couldn't find a solution, @vladbicu. Best of luck with your project and finding a solution for IE11.

**Comment by chenyulun** [comment]
Can proxy insetRule method？
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet


```js
// Object.keys(CSSStyleSheet.prototype)
// (9) ['ownerRule', 'cssRules', 'rules', 'addRule', 'deleteRule', 'insertRule', 'removeRule', 'replace', 'replaceSync']
// Some methods are supported only in higher versions and can be done without a proxy
var insertRuleFn = CSSStyleSheet.prototype.insertRule
CSSStyleSheet.prototype.insertRule =function(ruleStr,index) {
// console.log(ruleStr);
var legacyRuleStr = window.cssVarsSync ?  window.cssVarsSync(ruleStr) : ruleStr;
// console.log(legacyRuleStr);
 insertRuleFn.call(this, legacyRuleStr, index) }
```

**Comment by jhildenbiddle** [comment]
@chenyulun --

The challenge with an `insertRule` proxy (or any CSSOM proxy, for that matter) is that there is no indication of how "ready" the CSS is for processing. You either have to treat each rule as if it is the last and process it using what you know, or find some indicator to serve as a "ready" event like waiting some amount of time since the last CSSOM method call (`addRule`, `deleteRule`, `insertRule`, etc).

If rules are inserted in a very specific order, this is not an issue:

```js
styleElm.sheet.insertRule(':root { --color: red; }', 0);
styleElm.sheet.insertRule('p { color: var(--color); }', 0);
```

```css
p { color: red; }
```

But if rules are inserted out of order...

```js
styleElm.sheet.insertRule('p { color: var(--color); }', 0);
styleElm.sheet.insertRule(':root { --color: red; }', 0);
```

... or override previous values...

```js
styleElm.sheet.insertRule(':root { --color: red; }', 0);
styleElm.sheet.insertRule('p { color: var(--color); }', 0);
styleElm.sheet.insertRule(':root { --color: blue; }', 0);
```

... or invalidate previous values ...

```js
styleElm.sheet.insertRule(':root { --color: red; }', 0);
styleElm.sheet.insertRule(':root { --color: blue; }', 0);
styleElm.sheet.insertRule('p { color: var(--color); }', 0);
styleElm.sheet.deleteRule(1);
```

... things get complicated very quickly.

The ponyfill doesn't suffer from these problems because it doesn't being its work until the `DOMContentLoaded` event fires. This is a "good enough" signal that all CSS is ready for processing:

1. Get all CSS data from `<link>` and `<style>` elements
2. Parse CSS data
3. Store all custom property values
3. Replace all `var()` functions with custom property values
4. Inject `<style>` elements with transformed CSS after each `<link>` and `<style>` element processed

Could CSSOM method proxies work? Possibly, but it would be a significant amount of work and has the likely potential to perform poorly if/when previously processed rules need to be re-processed (see examples above). If someone were motivated, they could attempt it using the individual libraries in the [`src`](https://github.com/jhildenbiddle/css-vars-ponyfill/tree/master/src) directory of the repo.

**Comment by isocroft** [comment]
Hey @jhildenbiddle , i could take a stab at this.

What if you use the CSSOM interface to send custom events to another processing function that records and analyses any mutations made to a specific stylesheet element while also using a `setInterval(...)` to poll on the `textContent` property of the stylesheet element to correctly access all rule insertions/deletions and after word call a function to re-process everything (within a `requestIdleCallback(...)` workLoop to keep the main thread free of any janky-ness) or just the parts of styles that changes due to the rule insertions/deletions.

I could firstly create a custom CSS rule mutation observer by monkey-patching `.insertRule(...)` and `deleteRule(...)` like specified above by @chenyulun  and using custom events from the monkey-patching to start the `setInterval(...)` polling and finally call back into the already existing logic in `window.cssVarsSync(...)`

What do you think ? I have older browser i will like to support for this
