### ISSUE TITLE
What needs to be ponyfied ?

### ISSUE THREAD

**Issue by tristanbes** [jhildenbiddle/css-vars-ponyfill#20]
Hello,

I got one css file that contains all my variables on the `:root` scope (`1575-257888.css`).
I got only 1 other css (`app.css`) file that make use of those variables.

So If I want the best performance possible, do I need to include only the .css that contains the declaration of those variables ? Or only those 2 files listed above ?

Thanks you

**Comment by jhildenbiddle** [comment]
The ponyfill would need to process both files to 1) get the CSS custom property name/values from `1575-257888.css` and the 2) resolve the `var()` functions in `app.css` to static values.

```html
<head>
  ...
  <link rel="stylesheet" href="1575-257888.css">
  <link rel="stylesheet" href="app.css">
</head>
<body>
  ...
  <script src="https://unpkg.com/css-vars-ponyfill@1"></script>
  <script>
    cssVars();
  </script>
</body>
```

If performance is your primary concern, consider bundling your CSS into a single file since the ponyfill has to make a separate XMLHttpRequest for each external stylesheet. 

```html
<head>
  ...
  <!-- Combined Vars & Styles -->
  <link rel="stylesheet" href="app.css">
</head>
```

If you really want the "best performance possible", avoid XMLHttpRequests altogether by avoiding external stylesheets and applying CSS custom property declarations using a `<style>` tag:

```html
<head>
  ...
  <style>
    :root {
      --color: red;
    }

    body {
      background: var(--color);
    }
  </style>
</head>
```

This isn't very practical unless you have a very simple single page app/site or are using a tool like [Webpack](https://webpack.js.org/) or [Rollup](https://rollupjs.org/) to bundle-and-inject your CSS, but it is the most performant.

Finally, if your app uses additional stylesheets that do not contain CSS custom properties, tell the ponyfill to ignore them using [`options.include`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsinclude) or [`options.exclude`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsexclude). The ponyfill inspects each stylesheet and skips processing when appropriate, but it's faster to skip inspection by ignore these stylesheets entirely.

```html
<head>
  ...
  <!-- Combined Vars & Styles -->
  <link rel="stylesheet" href="app.css">

  <!-- Bootstrap -->
  <link rel="stylesheet" href="bootstrap.css">
</head>
<body>
  ...
  <script src="https://unpkg.com/css-vars-ponyfill@1"></script>
  <script>
    cssVars({
      exclude: '[href*="bootstrap"]'
    });
  </script>
</body>
```

Hope this helps!

**Comment by tristanbes** [comment]
It sure clarifies what needs to be included, thank you sir :-)
