### ISSUE TITLE
cssVars not displaying on IE11 within embedded iframe

### ISSUE THREAD

**Issue by wesleylhandy** [jhildenbiddle/css-vars-ponyfill#22]
I have a react-application that loads a .NET controlled form.

The react application is a form for collecting user information, selecting of products, and making donations. This data is sent to the .NET form which is loaded within an iframe controlled by React.

Both the React Form and the .Net Form utilize CSS variables and this ponyfill. However, on IE11, the variables load perfectly only on the React application. They fail to load on the iframed-app.

I include css-vars-ponyfill on both applications. I know the ponyfill runs on the iframe because I added an onComplete function that writes a message to the iframe DOM, but the styles are not updated within the iframe.

**Comment by wesleylhandy** [comment]
So, I have finally been able to get the function to run on the iframe. I did so by removing all options.

```
<link rel="stylesheet" href="/UI/CSS/variables.css" />
```

The following does not work in IE11 within my iframe:

```javascript
cssVars({
    include: 'link[href*="variables"]'
});
```

But this works:

```javascript
cssVars();
```

Works in all browsers for my React application:

```javascript
cssVars({
    updateURLs: false,
    watch: true,
   onComplete(cssText, styleNode) {
       updated = true;
       self.setState({...})
   }
});
```

**Comment by jhildenbiddle** [comment]
The ponyfill needs to process custom property declarations *and* style declarations that use those custom properties in `var()` functions. For example:

```css
/* file: variables.css */

:root {
  --mycolor: red;
}
```

```css
/* file: styles.css */

p {
  color: var(--mycolor);
}
```

The ponyfill needs to process *both* of these files in order to 1) get custom property values and 2) resolve `var()` functions to static values, then 3) append a new `<style>` tag to the DOM containing the legacy-compatible CSS.

```css
/* New <style id="css-vars-ponyfill"> node  */

p {
  color: red;
}
```

Given the example above, setting the `include` option to `link[href*="variables"]` tells the ponyfill to only process `variables.css` which contains no `var()` functions so there is no legacy-compatible CSS generated.
 
Hope this helps explain the behavior.

**Comment by wesleylhandy** [comment]
Thank you for responding. Makes sense. Got it working.
