### ISSUE TITLE
Problems together with angular6

### ISSUE THREAD

**Issue by snakevalley** [jhildenbiddle/css-vars-ponyfill#29]
Hi,

I want to use the ponyfill together with angular. Because it seems to be the only way, for using css variables together with the IE 11.

But sadly, it did not work and I'm not finding the problem.

We have the requirnment, to make our application themeable during runtime. So, we put a variable in our styles.css file. 
`:root {
    --headerBackgroundColor: '#444444'
}`

In the header component css file, we have something like

`.mat-toolbar.mat-primary {
  background-color: var(--headerBackgroundColor);
}`

During init of the angular app, we call cssvars({..}) method. 

But nothing hapens in the IE. On Chrome, Firefox and all modern browsers it worked. But on IE not. In the debug mode of IE I can see, that still background-color: var(--headerBackgroundColor); is set. 

Have you any advice, what went wrong?

Best regards
Jochen

**Comment by jhildenbiddle** [comment]
Hi @snakevalley.

Sounds like  `cssVars()` is being called before styles have been injected.

I put together a quick demo showing the ponyfill working with Angular:

* https://stackblitz.com/edit/css-vars-ponyfill-29?file=src/main.ts

The CSS generated by the ponyfill is displayed in the console. 

Note that I've set `include: 'style'` to reduce the noise (otherwise console output contains `<link>` CSS as well). If you know none of the `<link>` stylesheets contain CSS custom properties, this will prevent the ponyfill from doing unnecessary processing. I have also set `onlyLegacy: false` to force the ponyfill to work in modern browsers for the purpose of the demo.

Hope this helps. If not, let me know and we'll continue to troubleshoot.

**Comment by snakevalley** [comment]
Hi,

Yep... that was the problem. Thanks for the advice.

We try to ensure, that `cssVars()` is called after all css stuff is injected.

We use code-splitting to speed up the initial load of the whole application. That means, that we have to call `cssVars()` again, after another junk was loaded. 

Is there a way, that the ponyfill will notice changes to the style attributes in the header?

Btw: Great ponyfill! It helps us a lot for supporting the microsoft hell. Thanks a lot for this!

Regards
Jochen

**Comment by jhildenbiddle** [comment]
See [`options.watch`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionswatch).

Good to hear the ponyfill is working well for you!

**Comment by snakevalley** [comment]
we tried this already and it seems to work in Chrome and Firefox. But on IE11, the results are not deterministic.

On our root component we do this in ngOnInt

`private applyDefaultTheme() {
    cssVars({
      variables: new DefaultTheme(),
      watch: true
    });
    this.backend.loadTheme().subscribe(theme => {
      cssVars({
        variables: theme,
        watch: true
      });
    });
 }`

There we set the default theme and we start loading a dynamic theme from the server. The server theme must not be complete. So it can overwrite just a part of the default theme. 

With watch enabled, the default theme is present and the dynamic loading has no effect at the end. But only on IE 11.

Regards
Jochen

**Comment by jhildenbiddle** [comment]
Interesting.

I'm not familiar with Angular so I can't comment on the specifics, but the implementation above does not look like it is aligned with how the `watch` option is currently implemented in the ponyfill.

The `watch` implementation is intended to be set once, observe the DOM for `<style>` and `<link>` mutations, then call the ponyfill automatically when an appropriate `<style>` and `<link>` mutation is detected. There's no need to call `cssVar()` with `watch` multiple times (the option is ignored if `watch` was previously set) and the only time custom variables can be passed to the ponyfill using `options.variables` is the first time it is called with the `watch` option.

Assuming Angular is just injecting `<style>` and/or `<link>` elements, you should be able to call `cssVars({ watch: true })` even before `ngOnInt` to create the MutationObserver, then just let the ponyfill handle injected `<style>` and/or `<link>` elements automatically.

I've updated the demo with the changes described above:

* https://stackblitz.com/edit/css-vars-ponyfill-29?file=src/main.ts

**Comment by jhildenbiddle** [comment]
Hey @snakevalley.

Let me know if the above works for you. If so, I'll close the issue. Thx!

**Comment by snakevalley** [comment]
Hi,

sorry, we have a deadline today. Because of that, I had not the time in the last 2 days. 

Tomorrow I planned to do the test for it. I hope it is ok, to let the issue open until tomorrow.

Regards
Jochen

**Comment by jhildenbiddle** [comment]
Of course! No rush. 😃

**Comment by snakevalley** [comment]
Hi,

yep, seems to work. The trick is, to call it only once. So we have to change a little bit the process. Currently, we set the default thema at the beginning and load a partial theme and inject that later. 

So, if the theme just overwrites one property, only that is changed and the rest stays default. That works in modern browsers very well. But in IE it seems to be a problem. But we can change the backend, that always a full theme is generated. 

Thanks for the adivce.

Regards
Jochen

**Comment by jhildenbiddle** [comment]
@waterplea --

The ponyfill does not presume it is safe to skip any previously processed `<link>` or `<style>` nodes because the CSS content of those elements may have changed.

You are correct about the internal optimization that allows the ponyfill to skip *processing* of blocks of CSS that do not contain CSS custom property declarations (e.g. `--color: red;`) or functions (e.g. `var(--color)`) but, to be clear, the content of these blocks will still be included in the final output when `onlyVars` is `false` (which is the default). In other words, it's an internal optimization to avoid doing unnecessary work, not a "feature" that affects the ponyfill-generated CSS output.

**Comment by waterplea** [comment]
I know, I used onlyVars and try to organize my styles in a way it wouldn't matter :)

How about adding a flag "immutable" to enable ponyfill skipping previously processed nodes? It would mean that style can only be added or removed in whole nodes so ponyfill would process:
1) only new nodes if just variable usage was added and all nodes that had declarations before 
2) if any node with declarations was added/removed — it would redo all nodes with vars

Maybe I'm too used to Angular mindset but it sounds strange for me to alter contents of STYLE tags in runtime :)
