### ISSUE TITLE
Can't get ponyfill to work with app that loads theme

### ISSUE THREAD

**Issue by mcblum** [jhildenbiddle/css-vars-ponyfill#32]
Hey! 

Thanks for writing this - it's much, much appreciated.

We have an Angular app that loads a theme that looks like this:
```
typography: {
        body: {
            color: '#333',
            fontSize: '18px',
            fontWeight: 400,
            letterSpacing: '0',
            lineHeight: '1.5',

            margin: '0 0 10px 0',
            padding: '0',

            desktopLarge: {},
            desktop: {},
            tablet: {},
            mobile: {
            }
        },
        ...
```

Those nested objects are then translated to var strings such as `--typography-body-font-weight` and we use `setStyle` to assign their values. This is working for modern browsers but does not (obviously) work in IE.

The code we're using to do this stuff looks like this:
```
private setStyles(styles, variables: any) {
        Object.keys(styles)
            .forEach((key: string) => {
                const value = this.parseValue(styles[key], variables);

                this.themeWrapper
                    .style
                    .setProperty(this.parseKeyName(key), value);
            });

            cssVars({
                shadowDOM: true,
                onlyLegacy: false
            });
    }
```
And `styles` looks like:
```
--elements-accordion-content-padding: "20px"
--elements-accordion-group-margin-after-accordions: "20px"
--elements-accordion-icon-padding-top: "20px"
```
Thanks for your help @jhildenbiddle!

**Comment by jhildenbiddle** [comment]
Hi @mcblum,

The ponyfill can only read CSS custom property values that are contained in `<link>` and `<style>` nodes in the DOM *or* passed via [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables).  Since you are setting CSS custom property values using `style.setProperty()`, the ponyfill has no way of detecting these values.

The easiest fix is to just pass the values to the ponyfill using [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables). This will update both legacy *and* modern browsers.

```javascript
cssVars({
  variables: {
    "--elements-accordion-content-padding": "20px",
    "--elements-accordion-group-margin-after-accordions": "20px",
    "--elements-accordion-icon-padding-top": "20px"
  }
});
```

Note that you don't need to set `onlyLegacy` to `true` for this to work. The ponyfill knows to use `setProperty()` in modern browsers and do it's thing for legacy browsers. The `onlyLegacy` option is used to tell the ponyfill to treat all browsers like legacy browsers which you probably don't want to do for performance reasons. It's most helpful for troubleshooting or fixing buggy CSS custom property implementations found in older versions of Edge.

Also, you only need to set `shadowDOM` to `true` if you are using custom elements that leverage CSS custom properties.

Finally, since you mentioned Angular you might find the [`options.watch`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionswatch) useful as well as #29.

Hope this helps. If not, let me know and we'll keep crackin' at it. 😄

**Comment by mcblum** [comment]
@jhildenbiddle THANK YOU. Yes, everything works and this is wonderful. Can I buy you a beer/coffee or something? This is such a fantastic and well-thought-out piece of software and you are so helpful. Let me know and thanks again!

Matt

**Comment by jhildenbiddle** [comment]
Wonderful! Happy to hear everything is working as expected. 😄

Thanks for the kind words, btw. If you feel compelled, a star on the repo and/or a tweet to spread the word are always very much appreciated.

Best to you and hope the project goes well!

**Comment by mcblum** [comment]
@jhildenbiddle I'm on it! Thanks again.
