### ISSUE TITLE
Nested Calc Inside a Media Query

### ISSUE THREAD

**Issue by Taantawan** [jhildenbiddle/css-vars-ponyfill#34]
Similar to the issue "root: inside a media query", the fixNestedCalc option seems not working when a varible is used inside a media query.

```
:root {
	--calc3: calc(100vh * 0.01);
	--calc2: calc(2px + var(--calc3));
	--calc1: calc(var(--calc2) * 2);
}

@media (min-width: 0px) {
	h1 {
	  color: var(--h1-color);
	  margin-bottom: var(--calc1);
}

```
This will result in "margin-bottom: calc(calc(2px + calc(100vh * 0.01)) * 2);" even when fixNestedCalc is set to true. When you take out the media query enclosure, it wlll work as expected as you get "margin-bottom: calc((2px + (100vh * 0.01)) * 2);".

**Comment by jhildenbiddle** [comment]
CSS custom properties don't work in media queries in modern browsers either. This is per the [specification](https://www.w3.org/TR/css-variables-1/#using-variables):

> The var() function can be used in place of any part of a value in any property on an element. The var() function can not be used as property names, selectors, or anything else besides property values. (Doing so usually produces invalid syntax, or else a value whose meaning has no connection to the variable.)

It's unfortunate because assigning breakpoint values to variables is a common use case for CSS preprocessors. Unfortunately, CSS custom properties don't work that way.
