### ISSUE TITLE
issue on IE10

### ISSUE THREAD

**Issue by valentin78** [jhildenbiddle/css-vars-ponyfill#38]
Got issue on IE10
ponyfill not working, but on IE11 work fine 

PS after investigating, found that if load cssVars after 1 sec (in setTimeout) all work fine
therefore, i guess it related to onLoad event, that not fired may be in IE10 and sometimes in IE11
so, I simple wrap my invoke cssVars(..) into 
document.addEventListener("DOMContentLoaded", function() { ... });
and now work perfectly

**Comment by rtynio** [comment]
Hi, for me still I receive an ugly message "Unable to get property 'responseURL' of undefined or null reference".

**Comment by jhildenbiddle** [comment]
@valentin78 @rtynio --

I found a bug in one of the ponyfill's dependencies that caused cross-domain AJAX requests to fail in IE10. This issue has been resolved in 1.15.1.

Give the updated version a shot and let me know if this resolves your issue. 

---

@valentin78 --

That's strange. The ponyfill already delays execution until the `DOMContentLoaded` event fires, so doing the same in your code shouldn't be necessary.

https://github.com/jhildenbiddle/css-vars-ponyfill/blob/95f47b28c4c7e494ba42865dbb89946234df8f9e/src/index.js#L395-L403

Perhaps your issue is also related the bug that has been addressed in 1.15.1. If not, let me know and I'll investigate further.

Thanks!

**Comment by valentin78** [comment]
> @valentin78 @rtynio --
> 
> I found a bug in one of the ponyfill's dependencies that caused cross-domain AJAX requests to fail in IE10. This issue has been resolved in 1.15.1.
> 
> Give the updated version a shot and let me know if this resolves your issue.
> 
> @valentin78 --
> 
> That's strange. The ponyfill already delays execution until the `DOMContentLoaded` event fires, so doing the same in your code shouldn't be necessary.
> 
> [css-vars-ponyfill/src/index.js](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/95f47b28c4c7e494ba42865dbb89946234df8f9e/src/index.js#L395-L403)
> 
> Lines 395 to 403 in [95f47b2](/jhildenbiddle/css-vars-ponyfill/commit/95f47b28c4c7e494ba42865dbb89946234df8f9e)
> 
>  // Delay function until DOMContentLoaded event is fired 
>  /* istanbul ignore next */ 
>  else { 
>      document.addEventListener('DOMContentLoaded', function init(evt) { 
>          cssVars(options); 
>   
>          document.removeEventListener('DOMContentLoaded', init); 
>      }); 
>  } 
> Perhaps your issue is also related the bug that has been addressed in 1.15.1. If not, let me know and I'll investigate further.
> 
> Thanks!

yeh, it delayed until page loaded, but not wait until css loaded
