### ISSUE TITLE
Getting started with css-vars-ponyfill

### ISSUE THREAD

**Issue by mark-norgate-landg** [jhildenbiddle/css-vars-ponyfill#39]
Hi there

I am working on an app that uses Custom CSS Properties and it needs to work in IE 11. I have had a look at this library but I can't really discern how to configure it properly.

Can you please give me some guidance? I have an Angular app and we are switching themes by using class selectors on `:root body`. The themes contain the variables. The code is working perfectly in Chrome et al, but doesn't work in IE 11. What are the steps to get the library to do its magic and fix my CSS? I know there is a lot of documentation around the `cssVars()` method, and I have looked at all the dependant projects; but I still can't get it working!

Please help a drowning developer!

I am using the following format for my variables:
```
$variables: (
  --box-shadow-color: var(--box-shadow-color),
  --page-background-color: var(--page-background-color),
}
```
and giving them these default values:
```
:root body {
  --box-shadow-color: rgba(0, 0, 0, 0.03);
  --page-background-color: #{$light-grey};
}
```
and then swapping them in and out by using classes:
```
:root body.theme-johnlewis {
  --box-shadow-color: rgba(0, 0, 0, 0.03);
  --page-background-color: #{$color-red};
}
```
Is this the right format to be using?

**Comment by jhildenbiddle** [comment]
Hi @mark-norgate-landg.

Per the docs, the ponyfill requires all CSS custom properties to be declared within `:root`-level declarations. It does not support "scoped" custom properties like the one you've listed above which target the `body` element.

Fortunately, there are several ways to work around this.

The easiest way to swap themes based on CSS custom properties is to call the ponyfill using [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables) to update custom property values.

1. Declare your default values with a `:root`-level declaration:

   ```css
   :root {
     --my-color1: red;
     --my-color2: green;
     --my-color3: blue;
   }
   ```

1. Call the ponyfill to transform CSS in legacy browsers. This will render your default theme.

   ```javascript
   cssVars();
   ```

1. To swap themes, call the ponyfill again using `options.variables` to update values:

   ```javascript
   cssVars({
     variables: {
       '--my-color1': 'purple',
       '--my-color3': 'orange'
     }
   });
   ```

   If you prefer, store your theme values in a named object and just pass that to the ponyfill:

   ```javascript
   const myTheme = {
     '--my-color1': 'purple',
     '--my-color3': 'orange'
   };

   cssVars({
     variables: myTheme
   });
   ```

Note that [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables) is unique in that it can update both modern and legacy custom property values even when [`options.onlyLegacy`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsonlylegacy) is `true`. Click the links and read the docs for details.

There are other ways to swap themes as well. For example, you could store each theme's custom property values in a separate stylesheet, include them as [alternate stylesheets](https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets), then enable/disable those sheets as needed to set a new active theme. You would then call `cssVars()` manually, or you could use [`options.watch`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionswatch) to have the ponyfill detect these changes and call itself automatically. This requires more JS to write and maintain on your end, but it would allow you to store your theme values in CSS files instead of JS (if that matters).

Hope this helps. Let me know how it goes.

Thanks!

**Comment by mark-norgate-landg** [comment]
Thanks a lot for your comprehensive response, I shall have a play and try to get it working.

Thanks again.

**Comment by mark-norgate-landg** [comment]
Hey dude. Just to let you know we refactored as you suggested in your first code snippet and we managed to get theming working with SASS/CSS Variables in IE 1..

So thanks a lot!

**Comment by jhildenbiddle** [comment]
You bet. Happy to hear everything is working. 😊

**Comment by mark-norgate-landg** [comment]
Just as a heads-up, we got theming working by having each theme in its own file which consists of lots of CSS variables, then we swap the CSS in and out to implement theming.

**Comment by jhildenbiddle** [comment]
Curious — how are you swapping the files in/out? Using alternate stylesheets? Adding/removing `<link>` or `<style>` tags? Changing `<link>` href attribute?

Im assuming I read your response correctly and that you aren’t using `options.variables`.

**Comment by mark-norgate-landg** [comment]
We're finding the link using `document.querySelector()` and changing the href (I think that's the attribute's name).

No we don't use `options.variables`. We needed to keep it all in stylesheets.

**Comment by jhildenbiddle** [comment]
Sounds good. 

FYI — check out `options.watch` If you aren’t using it already. It will detect changes to `<link>` href value and call the ponyfill again automatically.

**Comment by mark-norgate-landg** [comment]
Ok, thanks

**Comment by alex84G** [comment]
Hi, is there an example of how to switch the CSS vars in a separate stylesheets with Javascript?

**Comment by jhildenbiddle** [comment]
@alex84G --

The ponyfill ignores `<link>` elements that have been disabled, so you could include them initially, toggle the `disabled` attribute on `<link>` elements as needed, and then call the ponyfill again to regenerate CSS.

Or, if you have `options.watch` enabled, the ponyfill will call itself once the MutationObserver detects changes to the `disabled` attribute of `<link>` elements in the DOM.

**Comment by Drunkard69** [comment]
Just started using this. Works great in Angular 7 running locally, but deployed to IIS and its not working.  Any ideas?

**Comment by steven-hyde** [comment]
@Drunkard69 It doesn't seem to work with compiled Angular code. There's an issue about it here,
https://github.com/jhildenbiddle/css-vars-ponyfill/issues/77
