### ISSUE TITLE
A performance question

### ISSUE THREAD

**Issue by stratboy** [jhildenbiddle/css-vars-ponyfill#40]
Hi, thank you for your code. in your docs you state:

> The ponyfill will:
> 
>     Get the <link>, <style>, and @import CSS
>     Parse the CSS and convert it to an abstract syntax tree
>     Transform CSS custom properties to static values
>     Transforms relative url() paths to absolute URLs
>     Convert the AST back to CSS
>     Append legacy-compatible CSS to the DOM

Question: will it do all those tasks even in modern browsers or, will it stop before?

**Comment by jhildenbiddle** [comment]
The ponyfill does a one-time check to determine if the browser provides native support for CSS custom properties. If it does, then the default behavior is to do nothing when ‘cssVars()’ is called unless:

1. ‘options.onlylegacy’ is set to ‘false’
1. ‘options.variables’ is used to modify custom property values

Check the docs for details on each option.

**Comment by stratboy** [comment]
Ah, ...and a compatibility question: does the ponyfill also work on Android browser 4.4.2+?

**Comment by jhildenbiddle** [comment]
I haven’t tested it, but It should given that the ponyfill works all the way back to IE9.

Since Android supports multiple browsers, the answer will also depend on which browser you are using. I can run some tests if that would be helpful, but that won’t be until after the weekend.

**Comment by stratboy** [comment]
> Since Android supports multiple browsers

Pardon, I mean: the native Android browser (not chrome). 
If you have some page/demo which clearly and visually shows the ponyfill working, I can test for you (I still use an old smartphone for tests).

**Comment by jhildenbiddle** [comment]
The CodePen demo linked in the README is a good test, although I doubt CodePen supports Android 4.4x native browser (non-Chrome) so you’ll have to force the page into “full page” view:

https://codepen.io/jhildenbiddle/full/ZxYJrR/

**Comment by stratboy** [comment]
...Aaaand... It's not clear to me: should I only declare variables in `:root`?

Something like this won't work (by updating --distance via js)?

```
.slides{
  --distance : 0px;

  @for $i from 1 through 20{
    &[data-current="#{$i}"]{ transform: translate(calc(-100% * (#{$i} - 1) + var(--distance))); }
  }
}
```

**Comment by jhildenbiddle** [comment]
From the [Features](https://github.com/jhildenbiddle/css-vars-ponyfill#features) section:

> Custom property support is limited to :root declarations

The example CSS you've provided will work in modern browers, but it is not supported by the ponyfill because `--distance` is declared within the `.slides` class. Adding support for scoped properties to the ponyfill simply isn't practical for reasons explained in #26.

Since you mentioned "updating --distance via js", remember to use the ponyfill and [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/README.md#optionsvariables) to make your changes to ensure they are applied to both modern and legacy browsers. See the docs for details.

Regarding Edge, the ponyfill cannot assume when it is safe to override a browser's native CSS custom property implementation. Fortunately, you can tell the ponyfill when it is appropriate using [`options.onlyLegacy`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsonlylegacy) and basic browser detection:

```javascript
cssVars({
  // Treat Edge 15/16 as legacy
  onlyLegacy: !(/Edge\/15|Edge\/16./i.test(navigator.userAgent)),
});
```

Hope this helps.
