### ISSUE TITLE
Server side rendering support

### ISSUE THREAD

**Issue by waterplea** [jhildenbiddle/css-vars-ponyfill#47]
_**Edit**: Summarized everything in one message_

Hi there.

I just began learning server side rendering and I tried to set up `css-vars-ponyfill` to do everything on the back before HTML is visible to user. I've managed to get it to work by passing a document DOM imitation as `rootElement`:
```
cssVars({
    rootElement: documentRef,
    onlyLegacy: false,
    include: `link[rel=stylesheet], style[${POLYFILL_MARK}], style[${THEME}]`,
    onlyVars: true,
    updateDOM: false,
    onComplete: cssText => {
        this.onPolyfillComplete(cssText);
    },
});
```
Where `documentRef` is like document, but in Node emulation. I use `onlyLegacy: false` because I check browser myself — old Edge pretends to support CSS vars but does it very poorly so I ponyfill for it too. Also on the back `CSS` object does not exist so `cssVars` internal check would fail even on Chrome (in Server side rendering you have to determine browser from the user-agent sent in the HTTP request). `POLYFILL_MARK` and `THEME` are attributes that I mark `<style>` tags with if I need to process them, never mind that, just my particular implementation.

So I was getting an error: `ERROR RangeError: Maximum call stack size exceeded`.

Since `documentRef` is not really document but rather an imitation it is considered an Object by `mergeDeep` function inside `css-vars-ponyfill`. So it goes over everything inside it :) I've added early return to that function which solved the issue for me:
```
    if (Object.assign) {
        var args = new Array(arguments.length);
        for(var i = 0; i < args.length; ++i) {
            args[i] = arguments[i];
        }
        args.unshift({});

        return Object.assign.apply(this, args);
    }
```
Also had to make that document dummy pretend it's loaded, Domino (DOM in Node) sets readyState to "loading" by default.

With that I've managed to get it to work. Everything is ponyfilled before user gets it, so no flickering on IE, looks awesome. I know Object.assign is a shallow copy but from the options of the ponyfill it doesn't look like you need a deep merge, the only object is variables map which is a map and is only read and never written to. If you could make the change above to your ponyfill or maybe come up with another way to allow for DOM imitation to take place — you could add Angular Universal / Server Side Rendering / Domino support to you library :)

You could also make a change to this line:
`if (document.readyState !== "loading") {`
to something like this:
```
// if document is an object — we're in a backend DOM 
// imitation and we do not need to wait for page load
if (document.constructor === Object || document.readyState !== "loading") {
```
It would eliminate the need to pretend to be loaded.

**Comment by waterplea** [comment]
Ok. I think I've setup everything right, but I have an issue.

In my server environment I have 11 `<style>` tags that I try to ponyfill. They are inside a Domino emulation (DOM in Node — a library for DOM-like stuff in Node). I call cssVars as follows:
```
cssVars({
    rootElement: documentRef,
    onlyLegacy: false,
    include: `link[rel=stylesheet], style[${POLYFILL_MARK}], style[${THEME}]`,
    onlyVars: true,
    updateDOM: false,
    onComplete: cssText => {
        this.onPolyfillComplete(cssText);
    },
});
```
Where `documentRef` is like document, but in Node emulation. I use `onlyLegacy: false` because I check browser myself — old Edge pretends to support CSS vars but does it very poorly so I ponyfill for it too. `POLYFILL_MARK` and `THEME` are attributes that I mark `<style>` tags with if I need to process them, never mind that, just my particular implementation.

I'm getting this error:
```
ERROR RangeError: Maximum call stack size exceeded
    at eval (webpack:///./node_modules/css-vars-ponyfill/dist/css-vars-ponyfill.esm.js?:316:29)
    at Array.forEach (<anonymous>)
    at eval (webpack:///./node_modules/css-vars-ponyfill/dist/css-vars-ponyfill.esm.js?:312:26)
    at Array.reduce (<anonymous>)
    at mergeDeep (webpack:///./node_modules/css-vars-ponyfill/dist/css-vars-ponyfill.esm.js?:311:20)
    at eval (webpack:///./node_modules/css-vars-ponyfill/dist/css-vars-ponyfill.esm.js?:316:29)
    at Array.forEach (<anonymous>)
    at eval (webpack:///./node_modules/css-vars-ponyfill/dist/css-vars-ponyfill.esm.js?:312:26)
    at Array.reduce (<anonymous>)
    at mergeDeep (webpack:///./node_modules/css-vars-ponyfill/dist/css-vars-ponyfill.esm.js?:311:20)
```

I realize this ponyfill is not intended for Node usage, but maybe there's just something simple and adding ability to ponyfill for IE before user sees the page would be awesome!

**Comment by waterplea** [comment]
Ok, since `documentRef` is not really `document` but rather an imitation it is considered an Object by your mergeDeep function so it goes over everything inside it :) I've added early return to it which solved the issue for me:
```
    if (Object.assign) {
        var args = new Array(arguments.length);
        for(var i = 0; i < args.length; ++i) {
            args[i] = arguments[i];
        }
        args.unshift({});

        return Object.assign.apply(this, args);
    }
```
Also had to make that document dummy pretend it's loaded. Ended up with empty CSS as a result of polyfilling though :) Gonna keep digging, sorry for many posts :)

**Comment by waterplea** [comment]
Well, with that last change I've managed to get it to work. Everything is ponyfilled before user gets it, so no flickering on IE, looks awesome. I know Object.assign is a shallow copy but from the options of the ponyfill it doesn't look like you need a deep merge, the only object is variables map which is a map and is only read and never written to. If you could make the change above to your ponyfill or maybe come up with another way to allow for DOM imitation to take place — you could add Angular Universal / Server Side Rendering / Domino support to you library :) 

You could also make a change to this line:
`if (document.readyState !== "loading") {`
to something like this:
```
// if document is an object — we're in a backend DOM 
// imitation and we do not need to wait for page load
if (document.constructor === Object || document.readyState !== "loading") {
```
It would eliminate the need to pretend to be loaded (Domino sets readyState to "loading" by default).

**Comment by waterplea** [comment]
1) I know but ponyfill check CSS and CSS.supports which is not available for server side.
2) It looks like you try to make you ponyfill dependency-free so adding a lib would not be an option for you.
3) I know that it is not available for old browsers, that's why I've made an early return with `if (Object.assign) {`, if it's not available — it falls back to mergeDeep.
4) In Angular Universal (server side Angular) it is typical to use Domino library and that emulation has readyState which is `loading`. Basically now I set it to `interactive` when I call ponyfill and immediately after to what it was. It's a bit hacky but seems fine since it's just an emulation. If you could handle it somehow in your method — it would be cool, but very optional. The real problem is mergeDeep treating `document` emulation as object and going into infinite loop.

**Comment by jhildenbiddle** [comment]
Apologies for the delayed response, @waterplea. Getting back on track after the holidays...

After thinking about this a bit more, I'm not sure I understand the advantage of adding SSR support to this ponyfill when postcss (along with the [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) plugin) already handles transforming custom properties to static values on the server. Postcss is also well integrated with tools like webpack and rollup as well as the CLI. Perhaps there is something Angular-specific that I am unaware of or a particular use case that postcss cannot handle? 

I can think of only two scenarios where SSR + css-vars-ponyfill could provide functionality not available with postcss:

1. Processing external `<link>` stylesheets
1. ShadowDOM support

I believe the first option would work without issue because js-based DOM implementations like [jsdom](https://www.npmjs.com/package/jsdom) and [domino](https://www.npmjs.com/package/domino) provide XMLHttpRequest support. ShadowDOM support would not work because the polyfills required don't support legacy browsers. That means we're left with just `<link>` support, which I can't imagine is a common issue given how easy it is to work around (just a local copy for server-side processing).

FWIW, I'm not opposed to making the changes but I'd like to clearly understand what benefit SSR support provides over existing options before investing dev time.

Thanks!

**Comment by waterplea** [comment]
Hi @jhildenbiddle 

Angular is pretty good at being platform agnostic. You have the same app pretty much, just a few configurations around it — and you get all the same components rendering at the server as on the client. You even can retain events/focus so when server-side rendered content is immediately delivered you can start filling forms and when the whole app arrives the transition is seamless. You could probably write some specific configuration to precalculate custom properties, I'm not really sure what is the pipeline with angular and styles — I'm not that versed with infrastructure but the philosophy behind Angular and SSR is that you write your app in a way that works in both environments.

**Comment by jhildenbiddle** [comment]
I did a little more research on this...

The source of confusion (for me, at least) is that tools like `react-create-app` and `@angular/cli` already include both [webpack](https://webpack.js.org/) and [PostCSS](https://postcss.org/) which are the tools necessary to transform CSS custom properties to static values on the server. Simply adding the [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) plugin is all that needs to be done.

Unfortunately, this isn't as easy at it sounds.

Adding a new plugin requires modifying configuration files, but these configuration files are not easily modified when apps are created using `create-react-app` or `@angular/cli`. These tools are designed to hide the build complexity from users, and as a result prevent users from modifying their internal configurations. It seems that the inability to make even minor config changes has been [an issue](https://github.com/angular/angular-cli/issues/8427) that users have struggled with for a while now. An "eject" option was once available for Angular users that would expose all configuration files, but going this route means taking on responsibilities for *all* of the complex build configuration (Angular is no longer managing for you). This option has been disabled in Angular 6 so [new tools](https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21) have been created to fill the gap, but it seems like folks are struggling with these as well.

Yeesh.

The summary is that I think there is value in adding SSR functionality to the ponyfill. If it were easier to add PostCSS plugins to apps created with `create-react-app` and `@angular/cli` then I would argue that [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) is a better server-side solution due to the way it processes and outputs CSS. Until then, perhaps css-vars-ponyfill can make life easier for folks by including SSR support.

I'll dive into this next week. Thanks, @waterplea.

**Comment by waterplea** [comment]
Thanks, @jhildenbiddle. Like I said, the only thing **really** preventing it from working as is — the merge deep function. The rest is quality of life — I only encountered a small inconvenience with `document.readyState` dependency that I mentioned in the first post while firing up a starter app for Angular.

**Comment by jhildenbiddle** [comment]
An updated version of the ponyfill is available via the "ssr" branch.

To install via NPM:

```bash
npm i -D jhildenbiddle/css-vars-ponyfill#ssr
```

This version contains one change: the deep merge previously used to merge default and user options has been replaced with a shallow merge (using `Object.assign`). This is a non-breaking change that should address the main issue you were experiencing with Angular and [domino](https://www.npmjs.com/package/domino).

Regarding the `document.readyState` issue, this is not an issue with other JavaScript-based DOM implementations like [jsdom](https://github.com/jsdom/jsdom) which are also used for SSR. The `document.constructor === Object` fix suggested also returns inconsistent results in these two libraries (`true` for domino, `false` for jsdom), so this check is not a reliable way to test for server-side rendering. I'd prefer to avoid adding code that is library (Angular, React, Vue, etc.) or environment (Browser, Server, Node, etc.) specific unless absolutely necessary, so in this case I think it's best to manage domino's `readyState` within your application.

FWIW, I've also added jsdom to the list of browsers used for automated unit testing. All tests pass without issue. I would add domino as well, but it the necessary [launcher](https://github.com/CaerusKaru/karma-domino-launcher) for [karma](https://karma-runner.github.io/latest/index.html) was release only a few days ago and based on [this issue](https://github.com/karma-runner/karma/issues/3251) it looks like it isn't ready for prime time yet.

Give the new version a shot and let me know how it works. If all goes well I'll publish it to npm as soon as I get the thumbs up.

**Comment by jhildenbiddle** [comment]
@waterplea ☝️

**Comment by waterplea** [comment]
Right, sorry @jhildenbiddle, forgot to give it a shot. Works fine with my setup, pretty sure it should work with other SSR frameworks. Thank you!

**Comment by jhildenbiddle** [comment]
No worries, @waterplea. Just wanted to make sure we addressed the issue before publishing.

New version (1.16.3) has been published to NPM.

Thx!
