### ISSUE TITLE
Parse error - missing "}" on IE11 and vue/vuetify

### ISSUE THREAD

**Issue by shaikemarc** [jhildenbiddle/css-vars-ponyfill#49]
HI,

Am trying to use the ponyfill with vue/vuetify for IE11.
 
The code that im using is:
`cssVars({
            silent: false, // default,
            watch: true,
            onSuccess(cssText, node, url) {
              console.log("onSuccess1",arguments);
            },
            onComplete(cssText, node, url) {
              console.log("onComplete",arguments);
            },
            onWarning(message) {
              console.log("onWarning",arguments); // 1
            },
            onError(message, node, xhr, url) {
              console.log("onError", arguments); // 1
            }
          });`

and its been called on mount of my app. The app uses a url based css and also  :root {...} which is created/injected by vuetify once it's been loaded.

What im getting (IE11)  are the following events:
- onSuccess - for the url based css 
- onError - missing "}" - it seems that here, the node that produced the err is the link with the very same href of the css.
- onComplete - this one seems to have transformed css...

After that no transformed style is adding to the body, IE still displays incorrect styles.

Any suggestion?
thanks!

**Comment by jhildenbiddle** [comment]
Hi @shaikemarc.

The ponyfill is telling you via the `onError()` callback that it has detected a missing brace in your CSS which prevents it from processing your CSS. Fortunately the other `onError()` arguments give you everything you need to troubleshoot the issue:

* The `node` argument is a reference to the `<link>` or `<style>` node the triggered the error.
* The `xhr` argument is a reference to the [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) object when `node` is a `<link>`, providing access to the `responseText` and `status` of the request.
* The `url` argument the a `<link>` `href` when `node` is a `<link>`.

Suggestions:

1. Inspect the CSS from the `node` that triggered the issue to determine where the missing brace (`}`) should be. 
1. If you don't find a missing brace, inspect the stylesheet located just *before* the `onError()` `node` since that stylesheet should be triggering the issue as well.
1. Verify via the XHR object `responseText` or your browser's developer tools that the AJAX request made by the ponyfill for external `<link>` stylesheets are coming back as expected. For example, if an external stylesheet is being served from another domain that is not CORS enabled, the ponyfill cannot access the CSS for that stylesheet via AJAX.

If all of the above fails to address the issue, try reducing your stylesheets down to a single stylesheet that causes the issue, then reduce try to reduce that stylesheet down to just the rule(s) that trigger the error. This will make further troubleshooting much easier.

Hope this helps. Let me know how it goes!

**Comment by shaikemarc** [comment]
Hi @jhildenbiddle ,

Thanks for the quick response. 
The node that throws the err is the `<link>` that contains the css URL.
The CSS is loaded from the same domain as the HTML, so no CORS here. 
Modern browsers deals with the css without any issue, perhaps they are less strict...

Ill take your advise and inspect the css. Is there any way to know, using the ponyfill, what rule/style/css element that triggers the err?

**Comment by jhildenbiddle** [comment]
The ponyfill currently does not provide error details like which ruleset triggered the error. Additional information could be provided, but it would be limited to X characters before or after where the parse error occurrent. Depending on what these characters are, this information may or may not be useful.

Try linting your CSS with [stylelint](https://stylelint.io/demo/). You can add it to your build process or use the online demo to test the contents of your linked stylesheet for errors. If your CSS is minified, you'll want to format it using something like [CSS Beautify](https://www.freeformatter.com/css-beautifier.html) first to avoid format-related lint errors, but know that a missing brace will most likely affect formatting tools as well.

**Comment by shaikemarc** [comment]
@jhildenbiddle ,
The issue was on our side, some intractable font's styles that were built incorrectly. Strange (or not at all) that chrome was OK with them. 
Now IE was convinced to work. 
Thanks, Great pkg!

**Comment by jhildenbiddle** [comment]
Glad you got it all worked out, @shaikemarc.
