### ISSUE TITLE
question: regarding pollyfill conversion

### ISSUE THREAD

**Issue by sheikalthaf** [jhildenbiddle/css-vars-ponyfill#53]
@jhildenbiddle Hi,

how much challenging is to create a pollyfill instead of ponyfill.
Have you analysed anything regarding this. I will help if you have any plan.

Thanks

**Comment by jhildenbiddle** [comment]
Hi @sheikalthaf,

This has been covered in a few other issues, most notably #26 where I provided an [explanation](https://github.com/jhildenbiddle/css-vars-ponyfill/issues/26#issuecomment-425682507) for why creating a polyfill (instead of a ponyfill) would be a significant amount of work and most likely wouldn't be performant enough for production use.

Quoting myself:

> All that being said, if someone wanted to take a crack at a spec-compliant ponyfill I'd be happy to help however I can. At this point, it's just not something I'm interested in driving based to the concerns outlined above.

I do appreciate the offer to help though. Sorry I can't provide a more encouraging response. 🤷‍♂️
