### ISSUE TITLE
CSS Variables replaced with empty strings

### ISSUE THREAD

**Issue by petermikitsh** [jhildenbiddle/css-vars-ponyfill#71]
Error:

CSS Variables seem to be replaced with empty strings. In this case, the background color of the table is incorrect. The IE 11 DOM Explorer panel shows the `background-color` as an empty string.

Expected UI (Chrome, Mac OS):

<img width="1420" alt="Screen Shot 2019-05-02 at 7 46 44 PM" src="https://user-images.githubusercontent.com/1571918/57117720-28555d00-6d13-11e9-8de0-dac668d77a04.png">

Actual UI (IE 11, Windows 8):

<img width="1451" alt="Screen Shot 2019-05-02 at 7 45 51 PM" src="https://user-images.githubusercontent.com/1571918/57117709-15db2380-6d13-11e9-8ee9-7555e561ab27.png">

Here's a closer look at the style tags in each:

<img width="1420" alt="Screen Shot 2019-05-02 at 7 54 38 PM" src="https://user-images.githubusercontent.com/1571918/57117886-30fa6300-6d14-11e9-8539-67f6cd17bce3.png">

<img width="1451" alt="Screen Shot 2019-05-02 at 7 54 47 PM" src="https://user-images.githubusercontent.com/1571918/57117895-39529e00-6d14-11e9-93e8-fa2849fdf76e.png">

**Comment by jhildenbiddle** [comment]
Hey @petermikitsh --

First, I noticed in your screenshots that you have a number of errors in your JavaScript console. Have you reviewed these to see if they are the cause? 

The ponyfill runs close to [500 automated tests](https://travis-ci.org/jhildenbiddle/css-vars-ponyfill/jobs/524245257#L535) across several browsers including IE9, so it is unlikely that the issue you're seeing is *just* a ponyfill issue.

The best way to troubleshoot issues like this is to create a demo on [stackblitz](https://stackblitz.com/) or [codesandbox](https://codesandbox.io/). This will give us a shared workspace to troubleshoot the problem. At the very least, I'd need to know how you are calling the ponyfill, what (if anything) you're doing with callbacks, etc.

**Comment by petermikitsh** [comment]
@jhildenbiddle I made a minimal reproduction here. The reproduction has no JS errors.

https://github.com/petermikitsh/css-ponyfill-bug/

The built files are available on GitHub pages: 

https://petermikitsh.github.io/css-ponyfill-bug/

Unfortunately, I had issues with stackblitz and codesandbox:

http://stackblitz.com/github/petermikitsh/css-ponyfill-bug
https://codesandbox.io/s/github/petermikitsh/css-ponyfill-bug

**Comment by petermikitsh** [comment]
The ponyfill is called here: https://github.com/petermikitsh/css-ponyfill-bug/blob/master/index.js#L25-L27

**Comment by petermikitsh** [comment]
I did some more debugging. I tried switching from `<style>@import url(...)</style>` syntax to using the `link` element. And it works! See diff and screenshot below.

```diff
diff --git a/index.ejs b/index.ejs
index 73f0766..8c267e6 100644
--- a/index.ejs
+++ b/index.ejs
@@ -3,12 +3,10 @@
   <head>
     <meta charset="UTF-8">
     <title><%= htmlWebpackPlugin.options.title %></title>
-    <style type="text/css">
-      @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/theme.css");
-      @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/icons.css");
-      @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/navfont.css");
-      @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/application.css");
-    </style>
+    <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/theme.css'>
+    <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/icons.css'>
+    <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/navfont.css'>
+    <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/application.css'>
   </head>
   <body>
   </body>
```

<img width="1347" alt="Screen Shot 2019-05-05 at 10 49 56 AM" src="https://user-images.githubusercontent.com/1571918/57198079-92445100-6f23-11e9-9d70-17a1b7b4e4e8.png">

However, the docs do mention that `@import` is supported:

> Transforms <link>, <style>, and `@import` CSS

If my original usage of the style tag with `@import` is correct, it seems possible there could be a bug here.

**Comment by jhildenbiddle** [comment]
Thanks for creating the repo, @petermikitsh.

The issues you are experiencing are webpack-related, not ponyfill-related.

I've created a CodePen demo using the same `@import` statements used in your repo. This demo uses the ponyfill by itself without a bundler. The ponyfill processes the `@import` statements without issue.

* https://codepen.io/anon/pen/dEyJmM

The empty string issue occurs in your test repo even when the ponyfill is disabled. My guess is that somewhere in the webpack pipeline styles are being injected and read using [CSSOM APIs](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule). This performs better than injecting and reading `<link>` and `<style>` tags, but it creates headaches when working with CSS not supported by the browsers (e.g. IE + custom properties). See #23 for details.

So why did switching from `<style>` + `@import` to `<link>` elements work? Because webpack handles these scenarios differently. From what I can tell, webpack will fetch-and-replace `@import` CSS but leave `<link>` elements for the browser to handle. If webpack left the `@import` statements alone, the ponyfill would work as advertised.

**Comment by petermikitsh** [comment]
@jhildenbiddle, thank you for your reply.

I forked your pen here: https://codepen.io/anon/pen/QRwxMz

I added the following JavaScript:

```js
  const table = document.createElement('anj-table');

  table.columns = [{
    field: 'id'
  }, {
    field: 'value'
  }];

  table.dataSource = [{
    id: 1,
    value: 'one'
  }, {
    id: 2,
    value: 'two'
  }, {
    id: 3,
    value: 'three'
  }];

  document.body.appendChild(table);
```

Additionally, I added the following external script:

`https://unpkg.com/@anjuna/core@1.0.0-alpha.1/anjuna-core.js`.

In Chrome, we get the expected output:

<img width="1630" alt="Screen Shot 2019-05-06 at 5 21 42 PM" src="https://user-images.githubusercontent.com/1571918/57262965-745e1580-7023-11e9-8910-1200cc22b974.png">

However, still broken in IE (this is the same pen, but in debug view-- so the CodePen frame is hidden):

<img width="1748" alt="Screen Shot 2019-05-06 at 5 20 20 PM" src="https://user-images.githubusercontent.com/1571918/57263010-c43cdc80-7023-11e9-979a-1f661a7cee34.png">

Webpack has been totally removed from the picture. Since this is a stencil component library, I'll see if these learnings can be shared there, and hopefully we can get to the bottom of this. Thanks again!

Stencil issue: https://github.com/ionic-team/stencil/issues/1509

**Comment by jhildenbiddle** [comment]
@petermikitsh --

I continued looking into the issue after I posted my reply. I believe my explanation was incorrect. I'll look into this a bit more and report back what I find.

Apologies for the false conclusion. More to come... 😄

**Comment by jhildenbiddle** [comment]
Hi again, @petermikitsh --

It's been a while, but I decided to dive back into this issue today.

I read the [Stencil issue](https://github.com/ionic-team/stencil/issues/1509) above and @manucorporat's comment about dynamic `@import` statements caught my attention:

> The CSS shim can not intercept dynamic @import of CSS

This statement may or may not be true depending on how Stencil handles dynamic `@import` rules. There are a few important things to keep in mind:

* The ponyfill processes the **text content** of stylesheets applied via `<link>` and `<style>` elements. It does not use the [CSSOM](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model) to access live stylesheet data because custom property declarations (e.g. `--mycolor: red`) and functions (e.g. `color: var(--mycolor)`) are ignored by legacy browsers and will therefore be unavailable via CSSOM even though they exist in the stylesheet.

* The ponyfill's `watch` option uses a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to detect the following DOM changes: `<link>` and `<style>` elements being added/removed, or attribute changes on `<link>` and `<style>` elements. It currently does not detect changes to the text content of `<style>` elements, but this would be an easy fix to make simply by setting [MutationObserverInit.characterData](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/characterData) to `true`. I opted not to enable this functionality because it seemed unlikely that anyone would update CSS by modifying the text content of a `<style>` element.

Summary: If Stencil is dynamically adding `@import` statements by modifying the text content of `<style>` elements, the ponyfill can be updated to handle this. If Stencil is using CSSOM methods like [insertRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) to [deleteRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/deleteRule), then unfortunately legacy browser limitations prevent the ponyfill from detecting these changes. You may want reach out to the Stencil devs and ask them if this is an issue they would be willing to work on. If so, I am happy to make the necessary changes on my end.

In the meantime, I believe the [guidance](https://www.npmjs.com/package/@anjuna/core) you've provided about bundling [@anjuno/theme](https://www.npmjs.com/package/@anjuna/theme) CSS (instead of loading via CDN) is a reasonable workaround--although I was unable complete any requests to http://cdn.zuora.com.

For now, I'll assume this issue is resolved. If you determine a path forward that requires changes to the ponyfill, I am happy to reopen it.

Thanks!
