### ISSUE TITLE
does not work in IE11

### ISSUE THREAD

**Issue by phil123456** [jhildenbiddle/css-vars-ponyfill#75]
Hello

I installed your package in my app but in IE11 the css variables are not beeing used

my angular scss file

```
:root
{
	--primary-color:blue;
}
```

my component css

```
...
background-color: var(--primary-color);
```

it works in chrome, 

do I have to do something extra to make it work in IE11 ? include something ?

regards

**Comment by bp2008** [comment]
Hi.  Based on reading a number of other issues here, I believe you have to `include cssVars from '...';` and then call `cssVars();`.  

I just fought and fought to make this work in my legacy single-page-application which I do not want to infect with a transpilation process.

Here's what I did:

I found the part of `css-vars-ponyfill.min.js` which reads `(e=e||self).cssVars=t()` and changed it to `(e=e||self).cssVars=window.cssVars=t()`, thereby injecting the cssVars method into the window object in IE11, and *avoiding the need to load this as a module with something like RequireJS*.

I also conditionally loaded the script via this in a script block at the end of my `<body>` element.
```js
		if (!(window.CSS && window.CSS.supports && window.CSS.supports('--fake-var', 0)))
		{
			document.write('<script src="css-vars-ponyfill.min.js"><\/script>');
			document.addEventListener("DOMContentLoaded", function ()
			{
				if (typeof cssVars === "function")
					cssVars();
			});
		}
```

**Comment by phil123456** [comment]
I did not know I had to call cssVars();

it's not mentioned anywhere, I'll try your code

thanks for answering this

**Comment by proteus-aholt** [comment]
this should be documented somewhere.  Calling `cssVars()` after loading the library did the trick for me.  Thank you!

**Comment by bp2008** [comment]
Apparently this actually is documented in the Documentation as linked from the repository's README.md.

Many projects include basic installation and usage instructions directly in the readme however, so I totally understand how someone could miss this :)

**Comment by proteus-aholt** [comment]
I read the documentation (https://jhildenbiddle.github.io/css-vars-ponyfill/#/), but there is nothing that mentions this polyfill _will not work_ without calling `cssVars()` within your javascript.   

Yes, `cssVars` is mentioned, but only in the examples, specifically under the Javascript example, which _i_ understood to mean `cssVars` could be sued to populate css variables via javascript.  

I don't want to assume other people would understand it that way, though.

**Comment by phil123456** [comment]
easy to miss, it's not on the main page :-)
glad there is a solutions, this is a killer feature
let's hope that IE will disappear asap

**Comment by phil123456** [comment]
I have a problem thou, in my angular project cssVars() is not defined

I declared it in my main app.component.ts

`declare var cssVars: any;`

and I use it in onInit()

`cssVars();`

yet I get

`main.js:15598 ReferenceError: cssVars is not defined`

**Comment by phil123456** [comment]
found the answer here : https://stackblitz.com/edit/css-vars-ponyfill-29?file=src/main.ts

I finaly could make it work like this

```
cssVars({
  include: 'style',
  onlyLegacy: false,
  watch: true,
  onComplete(cssText, styleNode, cssVariables) {
    console.log(cssText);
  }
});
```

**Comment by acarnwath** [comment]
Does the import work in IE11? According to caniuse, it is not supported...
https://caniuse.com/#feat=es6-module

If you got it working in IE11, can you describe your full (end to end) implementation?

**Comment by Phil147** [comment]
I think the better spot to place the ponyfill is in the `ponyfills.ts` of your angular project. The ponyfill doesn't have to run in your applications lifecycle.

We have an application running this way which works perfectly fine on IE11. Don't forget other necessary polyfills for IE11 for angular.

Our config: 
```
cssVars({
   onlyLegacy   : true,
   shadowDOM: true,
   watch: true,
   updateURLs: false
 });
```

**Comment by Phil147** [comment]
@acarnwath the angular application gets transpiled so the `import` isn't a problem.

**Comment by acarnwath** [comment]
Ah, that is the disconnect. I am attempting to use this outside of an angular project

**Comment by jhildenbiddle** [comment]
@phil123456 and others --

Apologies for the delayed response. I was focused on other tasks for a few months, but I am now trying to catch up on GitHub issues.

The ponyfill does work with IE11, as verified by [over 500 automated tests](https://travis-ci.org/jhildenbiddle/css-vars-ponyfill) in all major browser going back as far as IE9.

It sounds like there are few issues here:

* As the name implies, this library is a *PONY*-fill, not a *POLY*-fill. For those unfamiliar with the difference, [here is a helpful article](https://ponyfoo.com/articles/polyfills-or-ponyfills) that describes the differences along with reasons why you might prefer one over the other.
* Some/all of the folks here missed the [Documentation](https://jhildenbiddle.github.io/css-vars-ponyfill) link at the top of the [README.md](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/README.md). That's good feedback. Perhaps I can add a "Usage" section to the README that directs readers to the [documentation site](https://jhildenbiddle.github.io/css-vars-ponyfill) in case they missed the link. If folks strongly prefer to have all documentation in the README instead of a separate site I can consider that, but personally I find the website easier to use.
* The [Examples](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=examples) section of the documentation website gives a **vanilla JS** example of how to use the ponyfill. There are no front-end framework/library-specific installation or usage notes (e.g. Angular, React, Svelte, Vue, etc.) because the assumption is devs will adapt the vanilla JS example as needed for their specific app/framework/library.

To be more specific:

* @phil123456: Call `cssVars()` from your `polyfills.ts` file as suggested by @Phil147. I am not an Angular expert, but this seems to be the way most people do it.
* @bp2008: Correct -- `import` and call `cssVars()`. If you don't want to include the ponyfill in your bundle, dynamic imports are a better option than hacking the ponyfill source (see #64).
* @proteus-aholt: See the [Examples](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=examples) section of the docs for usage details.
* @acarnwath: IE11 does not support [ES6 `import` statements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), but you can use a transpiler like [Babel](https://babeljs.io/) to convert ES6+ JS to ES5 JS (i.e. "new" JavaScript to "old" JavaScript). Another option is to just load the ponyfill using a `<script>` tag via CDN:
  
  ```html
  <!-- Latest v2.x.x -->
  <script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
  <script>
    cssVars({
      // Options...
    });
  </script>
   ```

Hopefully this helps. Additional feedback on how to update the docs and/or README to prevent this confusion in the future is welcome.

Thanks!

**Comment by bp2008** [comment]
Thanks @jhildenbiddle .  I do think a "Usage" heading linking to the documentation would be a good idea.  Just to get people started, I'd encourage a listing of the minimal code required to use it.

I swear though, people have forgotten how the web worked prior to JS modules.  I am pretty sure this does not actually work, unless I did something really bone-headed when I tried back in May.

``` js
<!-- Latest v2.x.x -->
<script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
<script>
  cssVars({
    // Options...
  });
</script>
```

**Comment by jhildenbiddle** [comment]
Hey @bp2008 --

Agreed on folks forgetting OG JS. I've definitely had a few of my own "wait, how do I... oh yeah, that's right!" moments of my own.

Here's a demo of the CDN usage: https://stackblitz.com/edit/css-vars-ponyfill-75. Everything works as expected. Since the stackblitz IDE interface is less-than-fun in IE11, I edit using a modern browser and load only the preview window in IE11: https://css-vars-ponyfill-75.stackblitz.io/.

**Comment by bp2008** [comment]
Sure enough, it works now.  I wonder why I needed to hack the library when I tried this earlier.  *sigh*

**Comment by proteus-aholt** [comment]
@jhildenbiddle 

I think the disconnect I had was the documentation examples are laid out in a way to make them seem exclusive.  I understood it as "you can include the ponyfill and just write your css vars like normal within your css, OR you can do it with javascript!".  In reality, you need to call `cssVars` in order for it to work at all, which isn't mentioned.

I think something like:

> you need to call `cssVars();` within your javascript, or the ponyfill will not function.

within the installation section would go a long ways in clearing up any confusion for future users.

**Comment by iamdevlinph** [comment]
Even with `cssVars();` this still doesn't work. I'm not sure what I'm missing here.

I also tried to do the `options.variables` but no luck.

```
cssVars({
  variables: {
    '--primary-color': 'red',
  },
});
```

**Comment by jhildenbiddle** [comment]
@iamdevlinph 

The ponyfill has been thoroughly tested and works in IE 11. If you are having issues, consider opening a new issue with either working demo or a more complete configuration copy/pasted here for review.

**Comment by xavadu** [comment]
FTR I have it running well with AOT Angular 10.
The condition is only to run `cssVars()` if the browser doesn't support it.

polyfills.ts
```
import cssVars from 'css-vars-ponyfill';
if (!(window.CSS && window.CSS.supports && window.CSS.supports('--a', '0'))) {
    cssVars({
        shadowDOM: true,
        watch: true,
        updateURLs: false
    });
}
```

**Comment by jhildenbiddle** [comment]
@xavadu --

You can do that, but you don't need to. The ponyfill does a similar check and exits on browsers with native support *unless* the `onlyLegacy` option is set to `false` (it's `true` by default).

**Comment by xavadu** [comment]
@jhildenbiddle oh, thanks, I understood from documentation that still the ponyfill was doing some work
