### ISSUE TITLE
Doesn't work with Angular 6 when built with production mode

### ISSUE THREAD

**Issue by chakib-mohamed** [jhildenbiddle/css-vars-ponyfill#77]
Hello,

It seems that the example provided in : https://stackblitz.com/edit/css-vars-ponyfill-29 dosn't work in IE11 when i start the application with production mode enabled : ng serve --prod
Do you have any idea of the origin of the problem ?

Thanks in advance.

**Comment by steven-hyde** [comment]
We have the same problem. Everything seems to work fine when debugging using localhost, however once we compile the code using Angular 6 CSS Vars no longer works in IE11.

Here is an example of what the CSS of a button we use looks like when compiled in Angular 6,
![IE11_Compiled](https://user-images.githubusercontent.com/50843990/58043796-227dbb00-7b0c-11e9-953a-ecefbcc5e79a.jpg)

And here is an example of the CSS of that same button using localhost debug of Angular 6,
![IE11_Debug](https://user-images.githubusercontent.com/50843990/58043862-55c04a00-7b0c-11e9-89b4-37953777cef6.jpg)

I would like to add some additional information. We use the "watch" config in order to support angular encapsulation. Items that are encapsulated are working properly even when compiled as long as we're using the watch command. Here is an example of that,
![IE11_AngularEncapsulation](https://user-images.githubusercontent.com/50843990/58043998-b485c380-7b0c-11e9-8f08-308983fe9c76.jpg)

It's only components that are not encapsulated that are not working.

**Comment by winnemucca** [comment]
@steven-hyde @chakib-mohamed  Does this not require a JavaScript option?  I opened up the stackblitz and see **:root**.   Still learning this myself, to be honest.  If you guys figured this out only using css I would love to see your approach.

**Comment by jhildenbiddle** [comment]
@chakib-mohamed, @steven-hyde, @winnemucca --

Apologies for the delayed response. I was focused on other tasks for a few months, but I am now trying to catch up on GitHub issues.

I make no claims of being an Angular expert so perhaps I'm missing something, but I was able to put together a demo of the ponyfill working with Angular 6 in production mode on StackBlitz:

* https://stackblitz.com/edit/css-vars-ponyfill-77

Setup was pretty simple once the basic Angular app was in place:

1. Install `css-vars-ponyfill` as a dependency
1. Enable legacy polyfills in `polyfills.ts`
1. Add `css-vars-ponyfill` to `polyfills.ts`
1. Add sample styles to `styles.css`
1. Call `enableProdMode()` in `main.ts` to enable production mode
1. Toggle the preview window in StackBlitz (required when swapping between dev/prod mode -- see [this StackOverflow answer](https://stackoverflow.com/questions/47983242/cannot-enable-prod-mode-after-setup) for details)

Tested in IE by loading the preview window only (https://css-vars-ponyfill-77.stackblitz.io/). Works as expected, with ponyfill-processed CSS available in the console.

<img width="441" alt="Screen Shot 2019-08-03 at 11 42 03 PM" src="https://user-images.githubusercontent.com/442527/62419561-616dd800-b648-11e9-88c4-94b6a605117d.png">

Happy to help investigate further if needed, but as I mentioned my Angular skills are limited.

**Comment by jhildenbiddle** [comment]
@chakib-mohamed, @steven-hyde, @winnemucca --

Since I have not heard back, I am going to assume this issue has been resolved. I am happy to investigate further if you are able to provide additional information that allows me to reproduce the error.

**Comment by mdonjones** [comment]
We were having the exact same issue - everything working fine on localhost, but after deployment components that were not encapsulated were not being properly styled in IE11. We managed to get around the issue by setting the `extractCss` compiler option in `angular.json` to false.
