### ISSUE TITLE
Relative background URLs not adjusted

### ISSUE THREAD

**Issue by thomasbuengener** [jhildenbiddle/css-vars-ponyfill#8]
relative background-urls are not adjusted correctly when styles are inserted from css files inside subdirectories (urls are relative to the css files location).

**Comment by jhildenbiddle** [comment]
Thanks, @thomasbuengener . Agreed this will need to be addressed.

My initial thought is to simply convert all relative `url(...)` values since there are many properties that will be affected. I already have logic in place to convert relative `@import` URLs to absolute URLs, so I should be able to leverage this to address background images as well. 

In the meantime, there are two options to work around this issue:

1. Use absolute instead of relative URLs.
2. Set `options.onlyVars` to `true`, which tells the ponyfill to only output CSS declarations that contain a CSS custom property. Depending on how your CSS is authored, this may or may not work for you. The only way to guarantee the correct cascade in all scenarios is to include all declarations (which is why it is the default), but this isn't always required. Obviously, this also won't work if you are specifying a relative URL using CSS custom properties (Ex: `--myurl: '../path/to/file';`).

I'll update the lib as you've requested, but I won't be able to get to it this week. Hopefully the suggestions above will help until then.

**Comment by thomasbuengener** [comment]
Hi,

Thanks a lot. Not in a hurry though.


Yours,
Thomas Büngener




On Wed, May 9, 2018 at 8:58 PM +0200, "John Hildenbiddle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, @thomasbuengener<https://github.com/thomasbuengener> . Agreed this will need to be addressed.

My initial thought is to simply convert all relative url(...) values since there are many properties that will be affected. I already have logic in place to convert relative @import URLs to absolute URLs, so I should be able to leverage this to address background images as well.

In the meantime, there are two options to work around this issue:

  1.  Use absolute instead of relative URLs.
  2.  Set options.onlyVars to true, which tells the ponyfill to only output CSS declarations that contain a CSS custom property. Depending on how your CSS is authored, this may or may not work for you. The only way to guarantee the correct cascade in all scenarios is to include all declarations (which is why it is the default), but this isn't always required. Obviously, this also won't work if you are specifying a relative URL using CSS custom properties (Ex: --myurl: '../path/to/file';).

I'll update the lib as you've requested, but I won't be able to get to it this week. Hopefully the suggestions above will help until then.

**Comment by jhildenbiddle** [comment]
Fixed in 1.6.0. Please see [`options.updateURLs`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsupdateurls) for details.
