### ISSUE TITLE
Getting "Object doesn't support property or method 'repeat'", while trying to update variables by recalling cssVars()

### ISSUE THREAD

**Issue by gith-amitm7** [jhildenbiddle/css-vars-ponyfill#83]

**Comment by gith-amitm7** [comment]
Browser: IE 11
///Code 
cssVars({
    onComplete: (cssText, styleElms, cssVariables, benchmark) => {
      console.log(`Colors updated!`);
    },
    watch: true,
    onlyLegacy: false,
    shadowDOM: true,
    watch: true,
    updateURLs: false
    // variables: themeColors                   //themeColors would be json having new color key value pairs
  });

Calling cssVars() with above params gives the TypeError mentioned in title.

**Comment by jhildenbiddle** [comment]
@gith-amitm7 --

There should be no issue calling the ponyfill multiple times. I've created a demo to demonstrate this:
 
* https://stackblitz.com/edit/css-vars-ponyfill-83

There is no call to a `repeat` method in the ponyfill source, so it is more likely that you are using something like [`String.prototype.repeat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat) in your source which is being called when you invoke `cssVars()` somehow. Since this method isn't supported by IE and isn't automatically polyfilled with tools like [babel](https://babeljs.io/), you're seeing the error in IE11. Just a guess.

Another tip: You probably don't want to call the ponyfill with `watch: true` multiple times. Doing so will remove any previously-created ponyfill MutationObserver and then create a new one. If you want to run the ponyfill with `watch: true` to automatically detect CSS changes ***and*** manually provide custom property changes with `options.variables`, this is the correct way:

1. Call the ponyfill with `watch: true` to create the MutationObserver:

   ```js
   cssVars({
     watch: true,
     onComplete(cssText, styleElms, cssVariables, benchmark) {
       console.log('Automatic ponyfill update');
     }
   });
   ```

1. Call the ponyfill again when you want manually update values (MutationObserver is unaffected):

   ```js
   cssVars({
     variables: {
       '--color': 'red'
     },
     onComplete(cssText, styleElms, cssVariables, benchmark) {
       console.log('Manual ponyfill update');
     }
   });
   ```

Hope this helps!
