### ISSUE TITLE
Internet Explorer 

### ISSUE THREAD

**Issue by lschweig** [jhildenbiddle/css-vars-ponyfill#87]
Hi, 

just had an issue with loading a font: 
url value:
//fonts.googleapis.com/css?family=Poppins%3A700

IE is not able to load the resource (starting line 108 of v2.0.2)
"SCRIPT8: Der Download für die angegebene Ressource ist gescheitert."

i could fix it by adding those lines
if(url.substr(0,2) == "//") {url = 'https:' + url;}

would be nice to have this fixed in the next release.

**Comment by jhildenbiddle** [comment]
@lschweig —

Can you provide example CSS that causes the issue? For example, loading the above font with the full `@import`  or `src` statement. I will need this in order to troubleshoot.

**Comment by jhildenbiddle** [comment]
@lschweig --

I have put together a [StackBlitz demo ](https://stackblitz.com/edit/css-vars-ponyfill-87) testing three ways of loading a font with a protocol-relative URL: `@font-face`, `@import`, and `<link>`.

```css
@font-face {
  /* ... */
  src: url(//fonts.gstatic.com/s/poppins/v8/pxiEyp8kv8JHgFVrJJfecnFHGPc.woff2) format('woff2');
}
```
```css
@import url('//fonts.googleapis.com/css?family=Poppins&display=swap');
``` 
```html
<link href="//fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
```

The ponyfill handles all three methods without issue in my testing. If you provide specifics so that I can reproduce the issue, I will investigate further. Until then, I will assume this issue has been resolved.
