### ISSUE TITLE
How to disable parsing the imports?

### ISSUE THREAD

**Issue by chief-jai** [jhildenbiddle/css-vars-ponyfill#92]
In my Angular 7 project, I tried to use this plugin and I'm seeing errors in the console

![image](https://user-images.githubusercontent.com/30712750/65426800-961f3400-de2e-11e9-9496-75e777a3c6da.png)

I have an import like this,
@import "~font-awesome/scss/font-awesome";

I don't see the issue if I comment the import

**Comment by jhildenbiddle** [comment]
@chief-jai --

This isn't a ponyfill issue. The resources being requested (`fontawesome-webfont.woff` and `fontawesome-webfont.ttf`) are not available at the specified location which is why you are seeing these errors. When you comment out the `@import` statement, that resource is no longer requested which is why you don't see the error.
