### ISSUE TITLE
IE11 callback when variables have updated?

### ISSUE THREAD

**Issue by evry-johber** [jhildenbiddle/css-vars-ponyfill#98]
Hi,

First of all, thanks for an excellent package. I'm updating css variables using `variables` when a user logs in to my application. In IE11, I'm experiencing a delay before the variables are updated. Is there any way to wait for the update to complete? As far as I understand, neither `onSuccess` nor `onComplete` are suitable here.

Thanks!

**Comment by jhildenbiddle** [comment]
Hi @evry-johber.

Which "update" are you referring to? If you want execute code after the ponyfill has completed parsing/transforming/appending legacy-compatible CSS, then the `onComplete` callback is what you're looking for.

Regarding the delay you're seeing, keep in mind that the time it takes for the ponyfill to parse-and-transform your CSS is a fraction of the time it takes for the browser to apply the new styles generated by the ponyfill to elements in the DOM.  If you're seeing a substantial delay, it most likely means the ponyfill is generating-and-appending a lot of CSS and/or you have a large number of DOM elements. See https://github.com/jhildenbiddle/css-vars-ponyfill/issues/93#issuecomment-536655003 for an example of how to reduce this delay.

Hope this helps. Let me know if I misunderstood your question. Happy to help further is necessary.

**Comment by evry-johber** [comment]
@jhildenbiddle Thanks for your input. It seems like `onComplete` does the trick after a closer look. However, I need to set `onlyLegacy` to `false` as stated in the docs in order to trigger the callback in modern browsers. I presume this created unnecessary overhead in modern browsers? If so, I suppose I need to do something like the following in order to have a normalized callback without a performance hit in modern browsers?

```
function updateVariables(onComplete) {
  cssVars({ variables: { '--color-primary':  'red' }, onComplete })
  if(isNativeSupport) {
    onComplete()
  }
}
```

**Comment by jhildenbiddle** [comment]
@evry-johber --

The current callback behavior removes the need to include `isNativeSupport`-like wrappers in callbacks when focusing primarily on legacy browsers (which is the most common use case). 

Your scenario is admittedly a little confusing because using the `variables` option results in the ponyfill updating both modern and legacy browsers, albeit using different methods. The important thing to understand is that in this scenario the ponyfill is *synchronous* in modern browsers and *asynchronous* in legacy browsers (which is why the callbacks are made available). This is because modern browsers apply `variables` values using the native [`setProperty()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty) method while legacy browsers fetch `<link>` and `@import` stylesheets via AJAX, transform CSS with the `variables` value(s), then append the results using new `<style>` elements.

So, if you want to execute code after the ponyfill has applied changes to modern and legacy browsers, you could do something like this:

```js
function updateCSSVars(newVariablesObj = {}) {
  const hasCSSVarSupport = typeof window !== 'undefined' && window.CSS && window.CSS.supports && window.CSS.supports('(--a: 0)');

  cssVars({
    variables: newVariablesObj,
    onComplete(cssText, styleElms, cssVariables, benchmark) {
      doLegacyStuff();
    }
  });

  if (hasCSSVarSupport) {
    doModernStuff();
  }
}
```

Then call `updateCSSVars()`:

```js
updateCSSVars({
  'color1': 'red',
  'color2': 'green',
  'color3': 'blue'
});
```

**Comment by evry-johber** [comment]
@jhildenbiddle Yep, got it, thank you!!

**Comment by evry-johber** [comment]
@jhildenbiddle What do you think about either exposing your `isNativeSupport` or always triggering `onComplete` from within your framework?

**Comment by jhildenbiddle** [comment]
Never say never, but it doesn't seem likely.

Providing an `isNativeSupport` flag would only be necessary if a single `onComplete` callback is invoked in all browsers. That would be a significant breaking change that would only benefit 1) people using `options.variables` that 2) want to execute code after changes are applied 3) in both modern and legacy browsers and 4) who aren't wiling to add a few extra lines to their callback (similar to the above). Aside from the breaking change, there's still potential for confusion regarding when the callback fires: does `onComplete` fire in modern browsers each time the ponyfill is called, or only when `options.variables` is used? It's easy to imagine scenarios where you would want it one way or the other.

Long story longer, this is why callbacks only fire in legacy browsers (or when `onlyLegacy` is set to `false`): it's easy to understand, works best for the most common scenarios, and is relatively simple to work around if necessary.

**Comment by evry-johber** [comment]
> Providing an isNativeSupport flag would only be necessary if a single onComplete callback is invoked in all browsers.

I would say quite the opposite. It's needed to create your sample function above. If I rely on a copy like your `hasCSSVarSupport` and the internal `isNativeSupport` implementation change in a future version, I can end up with my own callback never firing. But I suppose the implementation of `isNativeSupport` won't likely change, so I guess it's a non-issue.
